In [1]:
import pandas as pd
from datetime import date, timedelta
from datetime import datetime
import os
import shutil
import pathlib
from nbconvert import PythonExporter
import polars as pl
import glob
import time

In [2]:
def convert_to_datetime(struct_time):
    return datetime(*struct_time[:6])


def input_data(data_dir):
    """Read all xlsx/csv files in a directory into a single Polars DataFrame."""
    
    def read_file(filename):
        try:
            mtime = convert_to_datetime(time.localtime(os.path.getmtime(filename)))
            df = (pl.read_excel(filename, infer_schema_length=0) if filename.suffix.lower() == '.xlsx'
                  else pl.read_csv(filename, infer_schema_length=0,
                                   encoding='utf-8' if True else 'ISO-8859-1'))
            return df.with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                   pl.lit(mtime).alias('Export time'))
        except Exception:
            try:
                return (pl.read_csv(filename, infer_schema_length=0,
                                    encoding='ISO-8859-1', ignore_errors=True)
                        .with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                      pl.lit(mtime).alias('Export time')))
            except Exception as e:
                print(f"Error reading {filename}: {e}")
                return None

    dfs = [df for f in pathlib.Path(data_dir).glob('**/*.*')
           if f.suffix.lower() in ('.xlsx', '.csv') and (df := read_file(f)) is not None]
    
    if not dfs:
        return pl.DataFrame()

    col_dtypes = {col: {df[col].dtype for df in dfs if col in df.columns}
                  for col in set(col for df in dfs for col in df.columns)}
    dfs = [df.with_columns(pl.col(c).cast(pl.Utf8)
                           for c, t in col_dtypes.items() if c in df.columns and len(t) > 1)
           for df in dfs]

    return pl.concat(dfs, how='vertical')

In [3]:
notebook_dict = {
  'IEX_optimized.ipynb': 1,
  'RTA_optimized (1).ipynb': 1,
}

def convert_notebook(notebook_path):
    exporter = PythonExporter()
    output, _ = exporter.from_filename(notebook_path)
    return output

first_glob = os.path.expanduser("~").replace("\\", "/")
test_path  = f'{first_glob}/Concentrix Corporation'
if not os.path.exists(test_path):
    raise FileNotFoundError(f'Not found the path: {test_path}')

folder_paths = {
    'output_iex_base'     : f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE'
}

print(f"Currently using base directory: {first_glob}")
IEX_BASE = input_data(folder_paths['output_iex_base'])
IEX_BASE

Currently using base directory: C:/Users/huuchinh.nguyen

shape: (102_699, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Agent     ┆ Date      ┆ Start_Shi ┆ End_Shift ┆ … ┆ End_Actio ┆ sheet_nam ┆ Export    ┆ Generate │
│ ---       ┆ ---       ┆ ft        ┆ ---       ┆   ┆ n         ┆ e         ┆ time      ┆ Date     │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ datetime[ ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Agent:    ┆ 2026-01-0 ┆ 9:00 PM   ┆ 10:00 AM  ┆ … ┆ 10:30 PM  ┆ IEX_Base_ ┆ 2026-05-2 ┆ 1/13/26  │
│ 3000182   ┆ 5         ┆           ┆           ┆   ┆           ┆ 2026_01_0 ┆ 6         ┆ 3:36 AM  │
│ HOANG,    ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 11:20:33  ┆          │
│ THIPHUON… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-01-0 ┆ 9:00 PM   ┆ 10:00 AM  ┆ … ┆ 2:30 AM   ┆ IEX_Base_ ┆ 2026-05-2 ┆ 1/13/26  │
│ 3000182   ┆ 5         ┆           ┆           ┆   ┆           ┆ 2026_01_0 ┆ 6         ┆ 3:36 AM  │
│ HOANG,    ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 11:20:33  ┆          │
│ THIPHUON… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-01-0 ┆ 9:00 PM   ┆ 10:00 AM  ┆ … ┆ 3:30 AM   ┆ IEX_Base_ ┆ 2026-05-2 ┆ 1/13/26  │
│ 3000182   ┆ 5         ┆           ┆           ┆   ┆           ┆ 2026_01_0 ┆ 6         ┆ 3:36 AM  │
│ HOANG,    ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 11:20:33  ┆          │
│ THIPHUON… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-01-0 ┆ 9:00 PM   ┆ 10:00 AM  ┆ … ┆ 4:30 AM   ┆ IEX_Base_ ┆ 2026-05-2 ┆ 1/13/26  │
│ 3000182   ┆ 5         ┆           ┆           ┆   ┆           ┆ 2026_01_0 ┆ 6         ┆ 3:36 AM  │
│ HOANG,    ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 11:20:33  ┆          │
│ THIPHUON… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-01-0 ┆ 9:00 PM   ┆ 10:00 AM  ┆ … ┆ 4:45 AM   ┆ IEX_Base_ ┆ 2026-05-2 ┆ 1/13/26  │
│ 3000182   ┆ 5         ┆           ┆           ┆   ┆           ┆ 2026_01_0 ┆ 6         ┆ 3:36 AM  │
│ HOANG,    ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 11:20:33  ┆          │
│ THIPHUON… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Agent:    ┆ 2026-08-0 ┆ 6:00 AM   ┆ 3:00 PM   ┆ … ┆ 1:10 PM   ┆ IEX_Base_ ┆ 2026-07-3 ┆ 7/31/26  │
│ 3112809   ┆ 2         ┆           ┆           ┆   ┆           ┆ 2026_07_2 ┆ 1         ┆ 3:55 AM  │
│ Duong,    ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 17:52:41  ┆          │
│ ThiThuyD… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-08-0 ┆ 6:00 AM   ┆ 3:00 PM   ┆ … ┆ 3:00 PM   ┆ IEX_Base_ ┆ 2026-07-3 ┆ 7/31/26  │
│ 3112809   ┆ 2         ┆           ┆           ┆   ┆           ┆ 2026_07_2 ┆ 1         ┆ 3:55 AM  │
│ Duong,    ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 17:52:41  ┆          │
│ ThiThuyD… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-08-0 ┆ 6:00 AM   ┆ 3:00 PM   ┆ … ┆ 7:45 AM   ┆ IEX_Base_ ┆ 2026-07-3 ┆ 7/31/26  │
│ 3112809   ┆ 2         ┆           ┆           ┆   ┆           ┆ 2026_07_2 ┆ 1         ┆ 3:55 AM  │
│ Duong,    ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 17:52:41  ┆          │
│ ThiThuyD… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-08-0 ┆ 6:00 AM   ┆ 3:00 PM   ┆ … ┆ 8:00 AM   ┆ IEX_Base_ ┆ 2026-07-3 ┆ 7/31/26  │
│ 3112809   ┆ 2         ┆           ┆           ┆   ┆           ┆ 2026_07_2 ┆ 1         ┆ 3:55 AM  │
│ Duong,    ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 17:52:41  ┆          │
│ ThiThuyD… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Agent:    ┆ 2026-08-0 ┆ 6:00 AM   ┆ 3:00 PM   ┆ … ┆ 10:40 AM  ┆ IEX_Base_ ┆ 2026-07-3 ┆ 7/31/26  │
│ 3112809   ┆ 2         ┆           ┆           ┆   ┆           ┆ 2026_07_2 ┆ 1         ┆ 3:55 AM  │
│ Duong,    ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆ 17:52:41  ┆          │
│ ThiThuyD… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
for nbook in notebook_dict:
    if notebook_dict[nbook] == 0:
        print(f"Not executing notebook {nbook}.")
        continue
        
    nbook_path = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Python_Code/{nbook}'
    
    if os.path.isfile(nbook_path):
        print(f"Running notebook: {nbook}")
        try:
            script = convert_notebook(nbook_path)
            exec(script)
        except Exception as e:
            print(f"Error running notebook: {nbook}")
            print(str(e))
    else:
        print(f"Error: Notebook {nbook} not found.")

Running notebook: IEX_optimized.ipynb
--- FULL FOLDER PATHS LIST ---
input_iex: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
input_hc_master: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Master Database - 2026.xlsx
output_iex: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
output_iex_all: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_AGENT_IEX
output_iex_intervals: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
output_iex_base: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE
hc_extend_by_month: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
input_iex_schedule_adjustment: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/IEX Backdated Schedule Adjustment Log.xlsx

<string>:257: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
<string>:291: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

✅ Exported 18 file(s) to 'C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE':
   IEX_Base_2026_03_09.csv  (2 rows)
   IEX_Base_2026_03_16.csv  (13 rows)
   IEX_Base_2026_03_23.csv  (4 rows)
   IEX_Base_2026_03_30.csv  (3 rows)
   IEX_Base_2026_04_27.csv  (1 rows)
   IEX_Base_2026_05_04.csv  (3800 rows)
   IEX_Base_2026_05_11.csv  (3496 rows)
   IEX_Base_2026_05_18.csv  (4093 rows)
   IEX_Base_2026_05_25.csv  (4254 rows)
   IEX_Base_2026_06_01.csv  (4966 rows)
   IEX_Base_2026_06_08.csv  (4998 rows)
   IEX_Base_2026_06_15.csv  (5102 rows)
   IEX_Base_2026_06_22.csv  (4627 rows)
   IEX_Base_2026_06_29.csv  (5026 rows)
   IEX_Base_2026_07_06.csv  (4758 rows)
   IEX_Base_2026_07_13.csv  (5320 rows)
   IEX_Base_2026_07_20.csv  (5097 rows)
   IEX_Base_2026_07_27.csv  (4954 rows)
Valid weeks found: ['2026-05-04', '2026-05-11', '2026-05-18', '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15', '2026-06-22', '2026-06-29', '2026-07-06', '2026-07-13', '2026-07-20', '2026-07-27']

<string>:342: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Rows after filter: 60491
Weeks retained: ['2026-05-04', '2026-05-11', '2026-05-18', '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15', '2026-06-22', '2026-06-29', '2026-07-06', '2026-07-13', '2026-07-20', '2026-07-27']

<string>:587: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
<string>:790: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

=== STAGE 3: sorted_df rows ===

,Date,IEX_ID,Scheduled Activity,Datetime_Start_Action,Datetime_End_Action,First Shift,Open Time,Extra Time,NCNS,Target,Time_Of_Day,Shift Tracking
36636,2026-07-02,3000182,Extra Hours,2026-07-02 07:00:00,2026-07-02 10:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36637,2026-07-02,3000182,Unscheduled,2026-07-02 10:00:00,2026-07-02 19:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36638,2026-07-02,3000182,Extra Hours,2026-07-02 19:00:00,2026-07-02 21:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36639,2026-07-02,3000182,Open Time,2026-07-02 21:00:00,2026-07-02 22:15:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36640,2026-07-02,3000182,Break_1,2026-07-02 22:15:00,2026-07-02 22:30:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36641,2026-07-02,3000182,Open Time,2026-07-02 22:30:00,2026-07-03 03:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36642,2026-07-02,3000182,Lunch,2026-07-03 03:00:00,2026-07-03 04:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36643,2026-07-02,3000182,Open Time,2026-07-03 04:00:00,2026-07-03 05:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36644,2026-07-02,3000182,Break_2,2026-07-03 05:00:00,2026-07-03 05:15:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT
36645,2026-07-02,3000182,Open Time,2026-07-03 05:15:00,2026-07-03 06:00:00,2100-0600,7.5,5.0,0.0,12.5,9.0,PR - OT

=== STAGE 4: IEX_EXTEND rows (final output) ===

,Date,IEX_ID,Datetime_First_Start_Shift,Datetime_First_End_Shift,First Shift,Open Time,Extra Time,Target,Time_Of_Day,Shift Tracking
36636,2026-07-02,3000182,2026-07-02 21:00:00,2026-07-03 06:00:00,2100-0600,7.5,5.0,12.5,9.0,PR - OT

Valid weeks: [Timestamp('2026-05-04 00:00:00'), Timestamp('2026-05-11 00:00:00'), Timestamp('2026-05-18 00:00:00'), Timestamp('2026-05-25 00:00:00'), Timestamp('2026-06-01 00:00:00'), Timestamp('2026-06-08 00:00:00'), Timestamp('2026-06-15 00:00:00'), Timestamp('2026-06-22 00:00:00'), Timestamp('2026-06-29 00:00:00'), Timestamp('2026-07-06 00:00:00'), Timestamp('2026-07-13 00:00:00'), Timestamp('2026-07-20 00:00:00'), Timestamp('2026-07-27 00:00:00')]
Running notebook: RTA_optimized (1).ipynb
--- FULL FOLDER PATHS LIST ---
input_iex_rawdata: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
storage_iex_rawdata: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_IEX
input_agent_activity: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_ACTIVITY_FOR_REPORT
storage_agent_activity: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_ACTIVITY
input_iex: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
input_iex_intervals: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
input_pull_out: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Save/EXP Leave Management.xlsx
input_ramco_code: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_RAMCO_CODE
input_ramco_ot: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_OT_RAMCO_CODE
output_rta: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT
output_rta_all: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA
rta_intervals_output: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_ACTIVITY_INTERVALS
ramco_output: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata
hc_extend_by_month: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
resources: C:/Users/huuchinh.nguyen/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Resources

<string>:379: DeprecationWarning: `DataFrame.melt` is deprecated. Use `unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`

shape: (2_247, 7)
┌───────────┬────────────┬────────────────────┬───────┬───────────────┬──────────────┬─────────────┐
│ EID       ┆ Date       ┆ ot_type            ┆ hours ┆ nsa_authorize ┆ ot_authorize ┆ ot_status   │
│ ---       ┆ ---        ┆ ---                ┆ ---   ┆ ---           ┆ ---          ┆ ---         │
│ str       ┆ date       ┆ str                ┆ f64   ┆ str           ┆ str          ┆ str         │
╞═══════════╪════════════╪════════════════════╪═══════╪═══════════════╪══════════════╪═════════════╡
│ 103173195 ┆ 2026-06-12 ┆ OT2.0X: 1.0 hrs    ┆ 1.0   ┆               ┆ Authorized   ┆ (1.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103548833 ┆ 2026-05-01 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103082160 ┆ 2025-04-30 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103305160 ┆ 2026-02-16 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103173197 ┆ 2026-05-09 ┆ NSA: 7.0 hrs,      ┆ 4.0   ┆ Authorized    ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆ OT1.5X: 4.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ …         ┆ …          ┆ …                  ┆ …     ┆ …             ┆ …            ┆ …           │
│ 102029874 ┆ 2026-01-10 ┆ NSA: 2.0 hrs,      ┆ 4.0   ┆ Authorized    ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆ OT2.0X: 4.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103085298 ┆ 2026-03-12 ┆ OT2.0X: 4.5 hrs    ┆ 4.5   ┆               ┆ Authorized   ┆ (4.5 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103082121 ┆ 2026-07-23 ┆ NSA: 8.0 hrs,      ┆ 2.0   ┆ Authorized    ┆ Authorized   ┆ (2.0 hrs -  │
│           ┆            ┆ OT1.5X: 2.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103117188 ┆ 2026-02-05 ┆ OT2.0X: 7.0 hrs,   ┆ 10.0  ┆               ┆ Authorized   ┆ (10.0 hrs - │
│           ┆            ┆ OT2.7X: 3.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103117188 ┆ 2026-05-01 ┆ OT3.9X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
└───────────┴────────────┴────────────────────┴───────┴───────────────┴──────────────┴─────────────┘
shape: (5, 4)
┌────────┬───────────┬──────────────────────────┬────────────────────┐
│ Month  ┆ EID       ┆ employee_name            ┆ count_working_days │
│ ---    ┆ ---       ┆ ---                      ┆ ---                │
│ str    ┆ i64       ┆ str                      ┆ i32                │
╞════════╪═══════════╪══════════════════════════╪════════════════════╡
│ Apr-25 ┆ 101993774 ┆ HIEU THI TRAN            ┆ 22                 │
│ Apr-25 ┆ 102029874 ┆ THIEN THANH TOAN  TRUONG ┆ 20                 │
│ Apr-25 ┆ 102173363 ┆ THI NGOC BICH  TRAN      ┆ 23                 │
│ Apr-25 ┆ 102173384 ┆ HUU VINH  MAI            ┆ 22                 │
│ Apr-25 ┆ 102211178 ┆ THI QUYNH TRANG  NGUYEN  ┆ 22                 │
└────────┴───────────┴──────────────────────────┴────────────────────┘
['After Call Work', 'Available', 'Available Cases', 'Available Chat', 'Available Phone', 'Break', 'Coaching', 'End of Shift', 'HR Accom / Prayer', 'Login', 'Lunch', 'Not Ready', 'Outbound Call', 'Personal', 'Restroom', 'System Issue', 'Team Meeting', 'Training', 'Unavailable']
shape: (91, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Date_Conve ┆ Staff Hour ┆ Total      ┆ THT(In    ┆ Avail     ┆ Other Pro ┆ Non Produ ┆ Present   │
│ rted       ┆ (In Hours) ┆ Break (In  ┆ Hours)    ┆ Time(In   ┆ ductive   ┆ ctive Aux ┆ for Calcu │
│ ---        ┆ ---        ┆ Hours)     ┆ ---       ┆ Hours)    ┆ Aux(In    ┆ (In       ┆ lation    │
│ date       ┆ f64        ┆ ---        ┆ f64       ┆ ---       ┆ Hours)    ┆ Hours)    ┆ ---       │
│            ┆            ┆ f64        ┆           ┆ f64       ┆ ---       ┆ ---       ┆ u32       │
│            ┆            ┆            ┆           ┆           ┆ f64       ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2026-05-03 ┆ 55.890774  ┆ 10.918191  ┆ 27.779953 ┆ 16.67326  ┆ 0.41182   ┆ 0.107551  ┆ 11        │
│ 2026-05-04 ┆ 413.338608 ┆ 54.217021  ┆ 243.66982 ┆ 94.437557 ┆ 14.121649 ┆ 6.892559  ┆ 46        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-05-05 ┆ 454.340068 ┆ 67.110563  ┆ 198.57149 ┆ 166.73483 ┆ 10.468144 ┆ 11.455034 ┆ 49        │
│            ┆            ┆            ┆ 6         ┆ 1         ┆           ┆           ┆           │
│ 2026-05-06 ┆ 444.739234 ┆ 63.463804  ┆ 193.77541 ┆ 151.30191 ┆ 21.37914  ┆ 14.81896  ┆ 48        │
│            ┆            ┆            ┆ 2         ┆ 7         ┆           ┆           ┆           │
│ 2026-05-07 ┆ 436.811561 ┆ 58.676418  ┆ 263.66699 ┆ 87.28785  ┆ 18.420387 ┆ 8.759914  ┆ 49        │
│            ┆            ┆            ┆ 1         ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-07-28 ┆ 509.756399 ┆ 80.451946  ┆ 368.39343 ┆ 51.410179 ┆ 5.600066  ┆ 3.900775  ┆ 57        │
│            ┆            ┆            ┆ 4         ┆           ┆           ┆           ┆           │
│ 2026-07-29 ┆ 491.168703 ┆ 73.653719  ┆ 290.29612 ┆ 121.14486 ┆ 3.504319  ┆ 2.569672  ┆ 56        │
│            ┆            ┆            ┆ 6         ┆ 8         ┆           ┆           ┆           │
│ 2026-07-30 ┆ 561.036325 ┆ 85.099841  ┆ 321.77434 ┆ 144.83305 ┆ 6.689186  ┆ 2.639901  ┆ 63        │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 2026-07-31 ┆ 605.744799 ┆ 94.11891   ┆ 353.35355 ┆ 146.23729 ┆ 9.715374  ┆ 2.319668  ┆ 68        │
│            ┆            ┆            ┆ 8         ┆           ┆           ┆           ┆           │
│ 2026-08-01 ┆ 157.955729 ┆ 15.997906  ┆ 117.44024 ┆ 23.689013 ┆ 0.099552  ┆ 0.729013  ┆ 33        │
│            ┆            ┆            ┆ 4         ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
df_result rows: 10054
shape: (109, 5)
┌────────────────┬────────────┬──────┬─────────────────────┬─────────────────────┐
│ Date_Converted ┆ Date       ┆ rows ┆ Start_MIN           ┆ Start_MAX           │
│ ---            ┆ ---        ┆ ---  ┆ ---                 ┆ ---                 │
│ date           ┆ date       ┆ u32  ┆ datetime[μs]        ┆ datetime[μs]        │
╞════════════════╪════════════╪══════╪═════════════════════╪═════════════════════╡
│ 2026-05-03     ┆ 2026-05-04 ┆ 35   ┆ 2026-05-04 00:01:31 ┆ 2026-05-04 04:58:37 │
│ 2026-05-05     ┆ 2026-05-05 ┆ 61   ┆ 2026-05-05 05:51:59 ┆ 2026-05-05 14:59:30 │
│ 2026-05-06     ┆ 2026-05-06 ┆ 47   ┆ 2026-05-06 05:58:06 ┆ 2026-05-06 15:02:06 │
│ 2026-05-07     ┆ 2026-05-07 ┆ 68   ┆ 2026-05-07 05:58:14 ┆ 2026-05-07 14:58:03 │
│ 2026-05-08     ┆ 2026-05-08 ┆ 17   ┆ 2026-05-08 11:05:23 ┆ 2026-05-08 14:59:01 │
│ …              ┆ …          ┆ …    ┆ …                   ┆ …                   │
│ 2026-07-29     ┆ 2026-07-30 ┆ 116  ┆ 2026-07-30 00:02:44 ┆ 2026-07-30 05:51:02 │
│ 2026-07-30     ┆ 2026-07-30 ┆ 61   ┆ 2026-07-30 21:05:15 ┆ 2026-07-30 23:57:51 │
│ 2026-07-30     ┆ 2026-07-31 ┆ 94   ┆ 2026-07-31 00:04:49 ┆ 2026-07-31 05:59:14 │
│ 2026-07-31     ┆ 2026-07-31 ┆ 47   ┆ 2026-07-31 21:00:04 ┆ 2026-07-31 23:58:05 │
│ 2026-07-31     ┆ 2026-08-01 ┆ 86   ┆ 2026-08-01 00:09:25 ┆ 2026-08-01 05:59:58 │
└────────────────┴────────────┴──────┴─────────────────────┴─────────────────────┘
[DEBUG] Pre-groupby | rows=10054
[DEBUG] Date_Converted=06-08 | rows=192 | End Time MAX=2026-06-23 08:06:15
[DEBUG] First Shift unique (06-08): ['2000-0500']
['2026-05-04', '2026-05-11', '2026-05-18', '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15', '2026-06-22', '2026-06-29', '2026-07-06', '2026-07-13', '2026-07-20', '2026-07-27']
Bỏ qua RTA_REPORT tuần 2026-04-27 (spillover ca đêm Chủ Nhật).
Bỏ qua RTA_EXTEND tuần 2026-04-27.

In [5]:
def input_data(folder_path, sheet_name=None):
    file_paths = glob.glob(f"{folder_path}/*.xlsx") + glob.glob(f"{folder_path}/*.csv")
    df_list = []

    for file in file_paths:
        if file.endswith('.xlsx'):
            df = pl.read_excel(file, sheet_name=sheet_name, infer_schema_length=0)
        elif file.endswith('.csv'):
            try:
                df = pl.read_csv(file, encoding="utf-8", infer_schema_length=0)
            except:
                df = pl.read_csv(file, encoding="ISO-8859-1", ignore_errors=True, infer_schema_length=0)
        
        df = df.with_columns([
            pl.col(col).cast(pl.String) 
            for col in df.columns
        ])
        
        df_list.append(df)
    
    merged_df = pl.concat(df_list, how='vertical')

    return merged_df

In [11]:
pl.Config.set_tbl_rows(50)
pl.Config.set_tbl_cols(100)

def filter_shift_discrepancies(df_input) -> pl.DataFrame:
    if isinstance(df_input, pd.DataFrame):
        df = pl.from_pandas(df_input)
    else:
        df = df_input

    hc_mismatch_condition = (
        pl.col("hc_actual").cast(pl.Float64, strict=False).fill_null(0.0) !=
        pl.col("hc_present").cast(pl.Float64, strict=False).fill_null(0.0)
    )

    productivity_condition = (
        (pl.col("Target").cast(pl.Float64, strict=False).fill_null(0.0) > 3.75) &
        (pl.col("sum_productive").cast(pl.Float64, strict=False).fill_null(0.0) <= 3.0)
    )

    lob_condition = (
        ~pl.col("LOB").str.contains("Support", literal=True) &
        ~pl.col("LOB").str.contains("Training", literal=True)
    )

    shift_condition = (
        (~pl.col("First Shift").is_in(["Training", "Offline", "Off"])) &
        (~pl.col("Shift Tracking").is_in(["Training Offline", "Off Phone Misc", "PO"])) &
        (
            pl.col("Shift Tracking").is_in(["PR", "PR - OT"]) |
            (pl.col("sum_productive").cast(pl.Float64, strict=False).fill_null(0.0) > 0.0)
        )
    )

    result = df.filter(
        (hc_mismatch_condition | productivity_condition) &
        lob_condition &
        shift_condition
    )

    if "Date_Converted" in result.columns:
        result = result.sort("Date_Converted")

    return result


RTA_REPORT_GENERATE = input_data(f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA')
print(RTA_REPORT_GENERATE.columns)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Date_Converted').str.slice(0, 10).str.strptime(pl.Date, format='%Y-%m-%d'),
    pl.col('Target').cast(pl.Float64),
    pl.col('duration').cast(pl.Float64),
    pl.col('sum_productive').cast(pl.Float64),
    pl.col('start').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False),
    pl.col('end').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False),
    pl.col('IEX ID').cast(pl.Utf8).str.strip_chars().str.strip_chars('"').alias('IEX ID'),
])

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.filter(
    pl.col('duration').is_not_null() | (pl.col('Target') > 0)
)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Shift Tracking').cast(pl.Utf8).str.strip_chars(),
    pl.col('Open Time').cast(pl.Float64).fill_null(0.0),
    pl.col('Extra Time').cast(pl.Float64).fill_null(0.0),
])

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.when(pl.col('Shift Tracking') == 'HDL').then(0.5)
    .when(
        (pl.col('Shift Tracking').is_in(['PR', 'PR - OT', 'PO'])) &
        ((pl.col('Open Time') > 0) | (pl.col('Extra Time') > 0))
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking').is_in([
            'Training Offline', 'Sick Leave', 'Paid Leave', 'Billable Training'
        ])) & (pl.col('Open Time') == 0)
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking') != 'HDL') &
        (pl.col('Shift Tracking') != 'PR') &
        (pl.col('Open Time') == 0)
    ).then(0.0)
    .otherwise(None)
    .alias('hc_present')
])

filtered_data = RTA_REPORT_GENERATE.select([
    'Date_Converted', 'Employee Name', 'LOB', 'Detail Status', 'IEX ID', 'First Shift', 'Shift Tracking',
    'start', 'end', 'Target', 'duration', 'sum_productive', 'training-idle', 'Extra Time',
    'hc_schedule', 'hc_actual', 'hc_present'
])

filtered_data = filtered_data.with_columns([
    pl.col('hc_actual').cast(pl.Float64),
    pl.col('hc_present').cast(pl.Float64),
])

start_date = '2026-07-01'
end_date   = '2026-07-31'

filtered_data = filtered_data.sort('Date_Converted').filter(
    (pl.col('Date_Converted') >= pl.lit(start_date).str.strptime(pl.Date, format='%Y-%m-%d')) &
    (pl.col('Date_Converted') <= pl.lit(end_date).str.strptime(pl.Date, format='%Y-%m-%d'))
)

filtered_data_pd = filtered_data.to_pandas()

filtered_data_1 = filter_shift_discrepancies(filtered_data)

filtered_data_1 = filtered_data_1.with_columns([
    pl.col("First Shift").str.extract(r"^(\d{4})-\d{4}$", 1).alias("_s_start"),
    pl.col("First Shift").str.extract(r"^\d{4}-(\d{4})$", 1).alias("_s_end"),
]).with_columns([
    (pl.col("_s_start").str.slice(0,2).cast(pl.Int64, strict=False) * 60 +
     pl.col("_s_start").str.slice(2,2).cast(pl.Int64, strict=False)).alias("_s_start_min"),
    (pl.col("_s_end").str.slice(0,2).cast(pl.Int64, strict=False) * 60 +
     pl.col("_s_end").str.slice(2,2).cast(pl.Int64, strict=False)).alias("_s_end_min"),
    (pl.col("start").dt.hour().cast(pl.Int64) * 60 +
     pl.col("start").dt.minute().cast(pl.Int64)).alias("_a_start_min"),
]).with_columns([
    pl.when(pl.col("_s_end_min") < pl.col("_s_start_min"))
      .then(pl.col("_s_end_min") + 1440 - pl.col("_s_start_min"))
      .otherwise(pl.col("_s_end_min") - pl.col("_s_start_min"))
      .alias("_s_duration_min"),
    (pl.col("_a_start_min") - pl.col("_s_start_min")).alias("_diff"),
]).with_columns([
    pl.when(pl.col("_diff") < 0)
      .then(pl.col("_diff") + 1440)
      .otherwise(pl.col("_diff"))
      .alias("_a_rel_start"),
]).with_columns([
    pl.when(pl.col("_s_start").is_null() | pl.col("start").is_null())
      .then(pl.lit(None))
      .when(pl.col("_a_rel_start").cast(pl.Float64) < pl.col("_s_duration_min").cast(pl.Float64) / 2.0)
      .then(pl.lit("First"))
      .otherwise(pl.lit("Second"))
      .alias("HDL_Shift")
]).drop(["_s_start", "_s_end", "_s_start_min", "_s_end_min",
         "_s_duration_min", "_diff", "_a_rel_start", "_a_start_min"])

filtered_data_1

['Year', 'Month', 'Week_Monday', 'Date_Converted', 'Employee Name', 'Email Id', 'OracleID', 'IEX ID', 'Target', 'Datetime_Fluctuate_Start_Shift', 'Datetime_Fluctuate_End_Shift', 'Fluctuate Shift', 'Datetime_First_Start_Shift', 'Datetime_First_End_Shift', 'First Shift', 'Alias', 'LOB', 'LOB_2', 'LOB_3', 'Supervisor Name', 'Wave', 'Detail Status', 'Status', 'Time_Of_Day', 'Open Time', 'Extra Time', 'Break Time', 'Lunch Time', 'Training', 'NCNS', 'AL', 'Unplanned', 'Planned', 'Roster Presented', 'Roster Scheduled', 'Night_Shift', 'Shift Tracking', 'OT Type', 'Combined OT Range', 'OT PreShift', 'OT PostShift', 'start', 'end', 'total_time_chat_handle', 'sum_productive', 'break', 'lunch', 'coaching-idle', 'training-idle', 'outbound-idle', 'break_count', 'other_status', 'over_break', 'over_lunch', 'exceed_break', 'duration', 'hc_actual', 'hc_schedule', 'time_late', 'time_leave', 'lateness', 'adherence_time', 'ramco_marked', 'nsa_authorize', 'ot_authorize', 'hours', 'ot_status', 'ot_type', 'days_count', 'nm_group', 'nsa_group', 'ot_group']

shape: (7, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Dat ┆ Emp ┆ LOB ┆ Det ┆ IEX ┆ Fir ┆ Shi ┆ sta ┆ end ┆ Tar ┆ dur ┆ sum ┆ tra ┆ Ext ┆ hc_ ┆ hc_ ┆ hc_ ┆ HDL │
│ e_C ┆ loy ┆ --- ┆ ail ┆ ID  ┆ st  ┆ ft  ┆ rt  ┆ --- ┆ get ┆ ati ┆ _pr ┆ ini ┆ ra  ┆ sch ┆ act ┆ pre ┆ _Sh │
│ onv ┆ ee  ┆ str ┆ Sta ┆ --- ┆ Shi ┆ Tra ┆ --- ┆ dat ┆ --- ┆ on  ┆ odu ┆ ng- ┆ Tim ┆ edu ┆ ual ┆ sen ┆ ift │
│ ert ┆ Nam ┆     ┆ tus ┆ str ┆ ft  ┆ cki ┆ dat ┆ eti ┆ f64 ┆ --- ┆ cti ┆ idl ┆ e   ┆ le  ┆ --- ┆ t   ┆ --- │
│ ed  ┆ e   ┆     ┆ --- ┆     ┆ --- ┆ ng  ┆ eti ┆ me[ ┆     ┆ f64 ┆ ve  ┆ e   ┆ --- ┆ --- ┆ f64 ┆ --- ┆ str │
│ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ me[ ┆ ms] ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ str ┆     ┆ f64 ┆     │
│ dat ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ ms] ┆     ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     ┆     │
│ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ VUU ┆ Lod ┆ Non ┆ 308 ┆ 200 ┆ Uns ┆ 202 ┆ 202 ┆ 2.5 ┆ 3.5 ┆ 2.6 ┆ 0.0 ┆ 2.5 ┆ 1.0 ┆ 0.5 ┆ 0.0 ┆ Sec │
│ 6-0 ┆ TIE ┆ gin ┆ Lod ┆ 915 ┆ 0-1 ┆ che ┆ 6-0 ┆ 6-0 ┆     ┆ 925 ┆ 803 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ N   ┆ g   ┆ gin ┆ 5   ┆ 100 ┆ dul ┆ 7-1 ┆ 7-1 ┆     ┆ 61  ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ NHA ┆     ┆ g   ┆     ┆     ┆ ed  ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ Pro ┆     ┆     ┆     ┆ 07: ┆ 10: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 24: ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 19  ┆ 52  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ PHA ┆ Lod ┆ Lod ┆ 309 ┆ 210 ┆ PR  ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ Fir │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 211 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 107 ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-1 ┆ DAT ┆ g   ┆ g   ┆ 4   ┆ 100 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 7   ┆ 95  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ LOI ┆     ┆ Pro ┆     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 21: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 01: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 17  ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 311 ┆ 210 ┆ PR  ┆ 202 ┆ 202 ┆ 4.0 ┆ 4.6 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 017 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 301 ┆ 488 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ NGO ┆ g   ┆ g   ┆ 1   ┆ 100 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 58  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HOA ┆     ┆ duc ┆     ┆     ┆     ┆ 20: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆ 37: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ YEN ┆     ┆ n   ┆     ┆     ┆     ┆ 51  ┆ 39  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HO  ┆ Lod ┆ Lod ┆ 304 ┆ 120 ┆ HDL ┆ 202 ┆ 202 ┆ 1.7 ┆ 4.5 ┆ 2.3 ┆ 1.8 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ VAN ┆ gin ┆ gin ┆ 547 ┆ 0-2 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 414 ┆ 785 ┆ 162 ┆     ┆     ┆     ┆     ┆ st  │
│ 7-2 ┆ DAI ┆ g_N ┆ g   ┆ 6   ┆ 100 ┆     ┆ 7-2 ┆ 7-2 ┆     ┆ 39  ┆ 54  ┆ 736 ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ HAI ┆ est ┆ Nes ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ 127 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ing ┆ tin ┆     ┆     ┆     ┆ 12: ┆ 16: ┆     ┆     ┆     ┆ 277 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆ 09: ┆ 41: ┆     ┆     ┆     ┆ 215 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 05  ┆ 35  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ PHU ┆ Lod ┆ Lod ┆ 308 ┆ 050 ┆ PR  ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.9 ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ Fir │
│ 6-0 ┆ NG  ┆ gin ┆ gin ┆ 533 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 462 ┆ 813 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-2 ┆ NGO ┆ g   ┆ g   ┆ 8   ┆ 900 ┆     ┆ 7-2 ┆ 7-2 ┆     ┆ 56  ┆ 39  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 6   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TRA ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 08: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ M   ┆     ┆ tio ┆     ┆     ┆     ┆ 02: ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 55  ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ VO  ┆ Lod ┆ Lod ┆ 302 ┆ 200 ┆ PR  ┆ nul ┆ nul ┆ 7.5 ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 ┆ nul │
│ 6-0 ┆ MIN ┆ gin ┆ gin ┆ 648 ┆ 0-0 ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     ┆ l   │
│ 7-3 ┆ H   ┆ g   ┆ g   ┆ 4   ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ NHA ┆     ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ duc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 303 ┆ 220 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 5.1 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 ┆ Fir │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 668 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 228 ┆ 678 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-3 ┆ HOA ┆ g   ┆ g   ┆ 6   ┆ 700 ┆     ┆ 7-3 ┆ 8-0 ┆     ┆ 69  ┆ 69  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ NG  ┆     ┆ Pro ┆     ┆     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ LAM ┆     ┆ duc ┆     ┆     ┆     ┆ 22: ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ VU  ┆     ┆ tio ┆     ┆     ┆     ┆ 07: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 09  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [7]:
input_iex_atd = filtered_data_1.select(['Date_Converted', 'IEX ID', 'HDL_Shift'])
input_iex_atd

shape: (5, 3)
┌────────────────┬─────────┬───────────┐
│ Date_Converted ┆ IEX ID  ┆ HDL_Shift │
│ ---            ┆ ---     ┆ ---       │
│ date           ┆ str     ┆ str       │
╞════════════════╪═════════╪═══════════╡
│ 2026-07-12     ┆ 3089155 ┆ Second    │
│ 2026-07-15     ┆ 3092114 ┆ First     │
│ 2026-07-17     ┆ 3110171 ┆ Second    │
│ 2026-07-20     ┆ 3045476 ┆ First     │
│ 2026-07-26     ┆ 3085338 ┆ First     │
└────────────────┴─────────┴───────────┘

In [8]:
# ── NCNS / HDL rows từ RTA_REPORT_GENERATE ───────────────────────
ncns_hdl_data = RTA_REPORT_GENERATE.select([
    'Date_Converted', 'Employee Name', 'LOB', 'Detail Status', 'IEX ID', 'First Shift', 'Shift Tracking',
    'start', 'end', 'Target', 'duration', 'sum_productive', 'training-idle', 'Extra Time',
    'hc_schedule', 'hc_actual', 'hc_present'
]).with_columns([
    pl.col('hc_actual').cast(pl.Float64),
    pl.col('hc_present').cast(pl.Float64),
]).filter(
    (pl.col('Date_Converted') >= pl.lit(start_date).str.strptime(pl.Date, format='%Y-%m-%d')) &
    (pl.col('Date_Converted') <= pl.lit(end_date).str.strptime(pl.Date, format='%Y-%m-%d')) &
    (pl.col('Shift Tracking').is_in(["NCNS", "HDL"]))
).sort('Date_Converted')

# ── HDL_Shift column ─────────────────────────────────────────────
ncns_hdl_data = ncns_hdl_data.with_columns([
    pl.col("First Shift").str.extract(r"^(\d{4})-\d{4}$", 1).alias("_s_start"),
    pl.col("First Shift").str.extract(r"^\d{4}-(\d{4})$", 1).alias("_s_end"),
]).with_columns([
    (pl.col("_s_start").str.slice(0,2).cast(pl.Int64, strict=False) * 60 +
     pl.col("_s_start").str.slice(2,2).cast(pl.Int64, strict=False)).alias("_s_start_min"),
    (pl.col("_s_end").str.slice(0,2).cast(pl.Int64, strict=False) * 60 +
     pl.col("_s_end").str.slice(2,2).cast(pl.Int64, strict=False)).alias("_s_end_min"),
    (pl.col("start").dt.hour().cast(pl.Int64) * 60 +
     pl.col("start").dt.minute().cast(pl.Int64)).alias("_a_start_min"),
]).with_columns([
    pl.when(pl.col("_s_end_min") < pl.col("_s_start_min"))
      .then(pl.col("_s_end_min") + 1440 - pl.col("_s_start_min"))
      .otherwise(pl.col("_s_end_min") - pl.col("_s_start_min"))
      .alias("_s_duration_min"),
    (pl.col("_a_start_min") - pl.col("_s_start_min")).alias("_diff"),
]).with_columns([
    pl.when(pl.col("_diff") < 0)
      .then(pl.col("_diff") + 1440)
      .otherwise(pl.col("_diff"))
      .alias("_a_rel_start"),
]).with_columns([
    pl.when(pl.col("_s_start").is_null() | pl.col("start").is_null())
      .then(pl.lit(None))
      .when(pl.col("_a_rel_start").cast(pl.Float64) < pl.col("_s_duration_min").cast(pl.Float64) / 2.0)
      .then(pl.lit("First"))
      .otherwise(pl.lit("Second"))
      .alias("HDL_Shift")
]).drop(["_s_start", "_s_end", "_s_start_min", "_s_end_min",
         "_s_duration_min", "_diff", "_a_rel_start", "_a_start_min"])

print(f"NCNS: {len(ncns_hdl_data.filter(pl.col('Shift Tracking') == 'NCNS'))} rows  |  "
      f"HDL: {len(ncns_hdl_data.filter(pl.col('Shift Tracking') == 'HDL'))} rows  |  "
      f"Total: {len(ncns_hdl_data)} rows")

ncns_hdl_data

NCNS: 3 rows  |  HDL: 55 rows  |  Total: 58 rows

shape: (58, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Dat ┆ Emp ┆ LOB ┆ Det ┆ IEX ┆ Fir ┆ Shi ┆ sta ┆ end ┆ Tar ┆ dur ┆ sum ┆ tra ┆ Ext ┆ hc_ ┆ hc_ ┆ hc_ ┆ HDL │
│ e_C ┆ loy ┆ --- ┆ ail ┆ ID  ┆ st  ┆ ft  ┆ rt  ┆ --- ┆ get ┆ ati ┆ _pr ┆ ini ┆ ra  ┆ sch ┆ act ┆ pre ┆ _Sh │
│ onv ┆ ee  ┆ str ┆ Sta ┆ --- ┆ Shi ┆ Tra ┆ --- ┆ dat ┆ --- ┆ on  ┆ odu ┆ ng- ┆ Tim ┆ edu ┆ ual ┆ sen ┆ ift │
│ ert ┆ Nam ┆     ┆ tus ┆ str ┆ ft  ┆ cki ┆ dat ┆ eti ┆ f64 ┆ --- ┆ cti ┆ idl ┆ e   ┆ le  ┆ --- ┆ t   ┆ --- │
│ ed  ┆ e   ┆     ┆ --- ┆     ┆ --- ┆ ng  ┆ eti ┆ me[ ┆     ┆ f64 ┆ ve  ┆ e   ┆ --- ┆ --- ┆ f64 ┆ --- ┆ str │
│ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ me[ ┆ ms] ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ str ┆     ┆ f64 ┆     │
│ dat ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ ms] ┆     ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     ┆     │
│ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 308 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.7 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 986 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 372 ┆ 220 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ HA  ┆ g   ┆ g   ┆ 1   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 17  ┆ 38  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ TUA ┆     ┆ Pro ┆     ┆     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ duc ┆     ┆     ┆     ┆ 10: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THI ┆     ┆ tio ┆     ┆     ┆     ┆ 16: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ EN  ┆     ┆ n   ┆     ┆     ┆     ┆ 23  ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HUY ┆ Lod ┆ Lod ┆ 308 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ NH  ┆ gin ┆ gin ┆ 475 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 065 ┆ 133 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ NGO ┆ g   ┆ g   ┆ 6   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 72  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HUE ┆     ┆ duc ┆     ┆     ┆     ┆ 09: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TRA ┆     ┆ tio ┆     ┆     ┆     ┆ 59: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ n   ┆     ┆     ┆     ┆ 43  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 302 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.4 ┆ 4.4 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 645 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 890 ┆ 880 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-0 ┆ VIE ┆ g   ┆ g   ┆ 8   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 14  ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ T   ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TRI ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 00: ┆ 29: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 03  ┆ 23  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ K’  ┆ Lod ┆ Lod ┆ 308 ┆ 060 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ SON ┆ gin ┆ gin ┆ 477 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 339 ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ H   ┆ g   ┆ g   ┆ 0   ┆ 500 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 55  ┆ 53  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆     ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 11: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 00: ┆ 02: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 48  ┆ 51  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ VO  ┆ Lod ┆ Lod ┆ 305 ┆ 060 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ TRA ┆ gin ┆ gin ┆ 224 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 656 ┆ 298 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ N   ┆ g   ┆ g   ┆ 3   ┆ 500 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 27  ┆ 38  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ HIE ┆     ┆ Pro ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ duc ┆     ┆     ┆     ┆ 10: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ MAI ┆     ┆ tio ┆     ┆     ┆     ┆ 59: ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 19  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 302 ┆ 200 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 6.0 ┆ 4.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 647 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 929 ┆ 489 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ KHA ┆ g   ┆ g   ┆ 6   ┆ 500 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 42  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 6   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ BAO ┆     ┆ duc ┆     ┆     ┆     ┆ 19: ┆ 02: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THA ┆     ┆ tio ┆     ┆     ┆     ┆ 54: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ I   ┆     ┆ n   ┆     ┆     ┆     ┆ 35  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ K’  ┆ Lod ┆ Lod ┆ 308 ┆ 070 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ SON ┆ gin ┆ gin ┆ 477 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 718 ┆ 698 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ H   ┆ g   ┆ g   ┆ 0   ┆ 600 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 44  ┆ 75  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆     ┆     ┆ Pro ┆     ┆     ┆     ┆ 6   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 11: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 54: ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 48  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 300 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.2 ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 809 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 890 ┆ 758 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-0 ┆ SON ┆ g   ┆ g   ┆ 7   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 05  ┆ 55  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ G   ┆     ┆ Pro ┆     ┆     ┆     ┆ 6   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NGU ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ YEN ┆     ┆ tio ┆     ┆     ┆     ┆ 00: ┆ 18: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 48  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HUY ┆ Lod ┆ Lod ┆ 308 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ NH  ┆ gin ┆ gin ┆ 475 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 299 ┆ 838 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ NGO ┆ g   ┆ g   ┆ 6   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 9   ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 6   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HUE ┆     ┆ duc ┆     ┆     ┆     ┆ 09: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TRA ┆     ┆ tio ┆     ┆     ┆     ┆ 59: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ n   ┆     ┆     ┆     ┆ 59  ┆ 47  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 301 ┆ 110 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.9 ┆ 2.1 ┆ 1.6 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 132 ┆ 0-2 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 874 ┆ 876 ┆ 976 ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ THI ┆ g   ┆ g   ┆ 5   ┆ 000 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 76  ┆ 61  ┆ 022 ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ ANH ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆     ┆     ┆     │
│     ┆ DUO ┆     ┆ duc ┆     ┆     ┆     ┆ 16: ┆ 20: ┆     ┆     ┆     ┆ 011 ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆ 04: ┆ 03: ┆     ┆     ┆     ┆ 638 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 23  ┆ 38  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 311 ┆ 110 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.7 ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 277 ┆ 0-2 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 640 ┆ 804 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ QUO ┆ g   ┆ g   ┆ 9   ┆ 000 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 69  ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HUN ┆     ┆ duc ┆     ┆     ┆     ┆ 16: ┆ 19: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ G   ┆     ┆ tio ┆     ┆     ┆     ┆ 14: ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 00  ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HUY ┆ Lod ┆ Lod ┆ 309 ┆ 060 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.9 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ NH  ┆ gin ┆ gin ┆ 663 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 159 ┆ 897 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ QUA ┆ g   ┆ g   ┆ 7   ┆ 500 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 93  ┆ 43  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8   ┆ NG  ┆     ┆ Pro ┆     ┆     ┆     ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ANH ┆     ┆ duc ┆     ┆     ┆     ┆ 11: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 01: ┆ 56: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 03  ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HUY ┆ Non ┆ Non ┆ 309 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.8 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ NGU ┆ _Lo ┆ Lod ┆ 231 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 371 ┆ 355 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-0 ┆ YEN ┆ dgi ┆ gin ┆ 4   ┆ 400 ┆     ┆ 7-0 ┆ 7-0 ┆     ┆ 77  ┆ 35  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ NHA ┆ ng  ┆ g   ┆     ┆     ┆     ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ T   ┆     ┆ Pro ┆     ┆     ┆     ┆ 05: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ANH ┆     ┆ duc ┆     ┆     ┆     ┆ 16: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 20  ┆ 34  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 311 ┆ 210 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.3 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 017 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 729 ┆ 301 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-0 ┆ NGO ┆ g   ┆ g   ┆ 1   ┆ 600 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 2   ┆ 92  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HOA ┆     ┆ duc ┆     ┆     ┆     ┆ 01: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆ 37: ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ YEN ┆     ┆ n   ┆     ┆     ┆     ┆ 06  ┆ 28  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ CHI ┆ Lod ┆ Lod ┆ 309 ┆ 050 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.7 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ NH  ┆ gin ┆ gin ┆ 652 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 817 ┆ 807 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-1 ┆ NGO ┆ g   ┆ g   ┆ 4   ┆ 400 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 99  ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THU ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 13: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 41  ┆ 35  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ LE  ┆ Non ┆ Non ┆ 303 ┆ 220 ┆ NCN ┆ 202 ┆ 202 ┆ 0.0 ┆ 1.0 ┆ 0.6 ┆ 0.4 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ Fir │
│ 6-0 ┆ TRU ┆ _Lo ┆ Lod ┆ 507 ┆ 0-0 ┆ S   ┆ 6-0 ┆ 6-0 ┆     ┆ 872 ┆ 398 ┆ 474 ┆     ┆     ┆     ┆     ┆ st  │
│ 7-1 ┆ ONG ┆ dgi ┆ gin ┆ 1   ┆ 700 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 65  ┆ 14  ┆ 508 ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ THA ┆ ng  ┆ g   ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ 327 ┆     ┆     ┆     ┆     ┆     │
│     ┆ NH  ┆     ┆ Pro ┆     ┆     ┆     ┆ 22: ┆ 23: ┆     ┆     ┆     ┆ 907 ┆     ┆     ┆     ┆     ┆     │
│     ┆ NHA ┆     ┆ duc ┆     ┆     ┆     ┆ 09: ┆ 14: ┆     ┆     ┆     ┆ 986 ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ tio ┆     ┆     ┆     ┆ 02  ┆ 16  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HOA ┆ Lod ┆ Lod ┆ 310 ┆ 200 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.8 ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ NG  ┆ gin ┆ gin ┆ 955 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 157 ┆ 891 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ DAI ┆ g   ┆ g   ┆ 1   ┆ 500 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 52  ┆ 28  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ HAI ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 01: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 45  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ TRA ┆ Lod ┆ Lod ┆ 310 ┆ 210 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.1 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 964 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 595 ┆ 387 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ DUC ┆ g   ┆ g   ┆ 3   ┆ 600 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 88  ┆ 17  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ TIN ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 20: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 56: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 46  ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ DUO ┆ Lod ┆ Lod ┆ 311 ┆ 060 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ NG  ┆ gin ┆ gin ┆ 280 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 294 ┆ 433 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ THI ┆ g   ┆ g   ┆ 9   ┆ 500 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 24  ┆ 04  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ THU ┆     ┆ Pro ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ Y   ┆     ┆ duc ┆     ┆     ┆     ┆ 10: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ DUO ┆     ┆ tio ┆     ┆     ┆     ┆ 53: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ n   ┆     ┆     ┆     ┆ 47  ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ PHA ┆ Non ┆ Non ┆ 308 ┆ 210 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.0 ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ M   ┆ _Lo ┆ Lod ┆ 878 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 797 ┆ 828 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ THI ┆ dgi ┆ gin ┆ 3   ┆ 600 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 74  ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ MIN ┆ ng  ┆ g   ┆     ┆     ┆     ┆ 6   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ H   ┆     ┆ Pro ┆     ┆     ┆     ┆ 01: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THU ┆     ┆ duc ┆     ┆     ┆     ┆ 55: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 23  ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 302 ┆ 120 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.9 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 644 ┆ 0-2 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 177 ┆ 064 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ THI ┆ g   ┆ g   ┆ 4   ┆ 100 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 74  ┆ 69  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ HAI ┆     ┆ Pro ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ LIN ┆     ┆ duc ┆     ┆     ┆     ┆ 11: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ H   ┆     ┆ tio ┆     ┆     ┆     ┆ 56: ┆ 51: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 32  ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 302 ┆ 220 ┆ HDL ┆ 202 ┆ 202 ┆ 3.2 ┆ 4.2 ┆ 3.9 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Sec │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 970 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 448 ┆ 508 ┆     ┆     ┆     ┆     ┆     ┆ ond │
│ 7-1 ┆ PHU ┆ g   ┆ g   ┆ 6   ┆ 700 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 5   ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ OC  ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THI ┆     ┆ duc ┆     ┆     ┆     ┆ 02: ┆ 07: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ EN  ┆     ┆ tio ┆     ┆     ┆     ┆ 58: ┆ 13: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 38  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ VUU ┆ Lod ┆ Non ┆ 308 ┆ 200 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 3.7 ┆ 3.7 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ TIE ┆ gin ┆ Lod ┆ 915 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 929 ┆ 905 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-1 ┆ N   ┆ g   ┆ gin ┆ 5   ┆ 500 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 3   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ NHA ┆     ┆ g   ┆     ┆     ┆     ┆ 6   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ Pro ┆     ┆     ┆     ┆ 20: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 38: ┆ 25: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 12  ┆ 47  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 303 ┆ 200 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 4.2 ┆ 4.1 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.5 ┆ Fir │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 667 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 953 ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆ st  │
│ 7-1 ┆ VO  ┆ g   ┆ g   ┆ 2   ┆ 500 ┆     ┆ 7-1 ┆ 7-1 ┆     ┆ 79  ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ DAN ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ G   ┆     ┆ duc ┆     ┆     ┆     ┆ 20: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ KHO ┆     ┆ tio ┆     ┆     ┆     ┆ 01: ┆ 19: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [9]:
# ── FILTER IEX_BASE BY filtered_data_1 ───────────────────────────────────────

IEX_BASE_filtered = IEX_BASE.with_columns(
    pl.col("Agent").str.extract(r"Agent:\s*(\d+)", 1).alias("IEX_ID"),
    pl.col("Date").cast(pl.Utf8)
)
filter_keys = (
    filtered_data_1
    .select([
        pl.col("IEX ID").cast(pl.Utf8).alias("IEX_ID"),
        pl.col("Date_Converted").cast(pl.Utf8).alias("Date")
    ])
    .unique()
)
IEX_BASE_filtered = IEX_BASE_filtered.join(filter_keys, on=["IEX_ID", "Date"], how="semi")
IEX_BASE_filtered = IEX_BASE_filtered.with_columns(
    pl.col("Date").str.strptime(pl.Date, format="%Y-%m-%d", strict=False),
    pl.col("Generate Date").str.strptime(pl.Datetime, format="%m/%d/%y %I:%M %p", strict=False),
    pl.col("Start_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.col("End_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.lit(None).cast(pl.Utf8).alias("Scheduled Activity"),
    pl.lit(None).cast(pl.Utf8).alias("Start_Action"),
    pl.lit(None).cast(pl.Utf8).alias("End_Action"),
    pl.col("sheet_name").str.strip_chars('"').str.replace(r"IEX_Base_", "").alias("sheet_name")
).drop("IEX_ID").unique().sort("Date")

with pl.Config(tbl_rows=50, tbl_cols=20, fmt_str_lengths=100, tbl_width_chars=500):
    display(IEX_BASE_filtered)

shape: (5, 10)
┌─────────────────────────────────────┬────────────┬─────────────┬───────────┬────────────────────┬──────────────┬────────────┬────────────┬─────────────────────┬─────────────────────┐
│ Agent                               ┆ Date       ┆ Start_Shift ┆ End_Shift ┆ Scheduled Activity ┆ Start_Action ┆ End_Action ┆ sheet_name ┆ Export time         ┆ Generate Date       │
│ ---                                 ┆ ---        ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---        ┆ ---        ┆ ---                 ┆ ---                 │
│ str                                 ┆ date       ┆ time        ┆ time      ┆ str                ┆ str          ┆ str        ┆ str        ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════════════════════╪════════════╪═════════════╪═══════════╪════════════════════╪══════════════╪════════════╪════════════╪═════════════════════╪═════════════════════╡
│ Agent: 3089155 Vuu, TienNhan        ┆ 2026-07-12 ┆ 20:00:00    ┆ 05:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_07_06 ┆ 2026-07-31 17:52:41 ┆ null                │
│ Agent: 3092114 Phan, DatLoi         ┆ 2026-07-15 ┆ 21:00:00    ┆ 06:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_07_13 ┆ 2026-07-31 17:52:41 ┆ 2026-07-21 04:16:00 │
│ Agent: 3110171 Nguyen, NgocHoangYen ┆ 2026-07-17 ┆ 21:00:00    ┆ 06:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_07_13 ┆ 2026-07-31 17:52:41 ┆ 2026-07-21 04:16:00 │
│ Agent: 3045476 Ho, VanDaiHai        ┆ 2026-07-20 ┆ 12:00:00    ┆ 21:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_07_20 ┆ 2026-07-31 17:52:41 ┆ 2026-07-30 04:40:00 │
│ Agent: 3085338 Phung, NgocTram      ┆ 2026-07-26 ┆ 05:00:00    ┆ 14:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_07_20 ┆ 2026-07-31 17:52:41 ┆ 2026-07-30 04:40:00 │
└─────────────────────────────────────┴────────────┴─────────────┴───────────┴────────────────────┴──────────────┴────────────┴────────────┴─────────────────────┴─────────────────────┘

In [10]:
# def get_xlsx_filenames(data_dir):
#     xlsx_files = []
#     for filename in pathlib.Path(data_dir).glob('**/*.xlsx'):
#         xlsx_files.append(filename.name)
#     return xlsx_files
# def create_dataframe_with_filenames(data_dir):
#     xlsx_filenames = get_xlsx_filenames(data_dir)
#     df = pd.DataFrame(xlsx_filenames, columns=['Filename'])
#     return df
# def get_latest_xlsx_files(df):
#     df = df[df['Filename'].str.match(r'\d{4}-\d{2}-\d{2}\.xlsx')]
#     df['Date'] = pd.to_datetime(df['Filename'].str.replace('.xlsx', ''), format='%Y-%m-%d')
#     df_sorted = df.sort_values(by='Date', ascending=False)
#     latest_files = df_sorted.head(8)['Filename'].tolist()
#     return latest_files
# def delete_all_xlsx_files(directory):
#     for filename in pathlib.Path(directory).glob('*.xlsx'):
#         os.remove(filename)
# def copy_latest_files(source_dir, dest_dir, latest_files):
#     for filename in latest_files:
#         source_path = pathlib.Path(source_dir) / filename
#         dest_path = pathlib.Path(dest_dir) / filename
#         shutil.copy(source_path, dest_path)

# source_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA'
# dest_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT'

# df = create_dataframe_with_filenames(source_dir)
# latest_files = get_latest_xlsx_files(df)
# delete_all_xlsx_files(dest_dir)
# copy_latest_files(source_dir, dest_dir, latest_files)