In [61]:
import os
import glob
import polars as pl
from datetime import datetime

# --- 1. SET UP PATHS ---
first_glob = os.path.expanduser("~").replace("\\", "/")
test_path = f"{first_glob}/Concentrix Corporation"
if not os.path.exists(test_path):
    raise FileNotFoundError(f"Not found the path: {test_path}")

folder_paths = {
    "rta_intervals_output": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_ACTIVITY_INTERVALS',
    "iex_intervals_output": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS',
    "output_non_compliance": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_NON_COMPLIANCE',
    "hc_extend_by_month": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month',
    
    "req_path": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OU.xlsx',
    "prod_path": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_PRODUCTIVE_REVENUE',
    "wfm_path": f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_WORKFORCE_VENDOR'
}

print("--- FULL FOLDER PATHS LIST ---")
for key, path in folder_paths.items():
    print(f"{key}: {path}")

print("-" * 60)

output_folder = folder_paths["output_non_compliance"]
os.makedirs(output_folder, exist_ok=True)

# --- 2. DEFINE DATA LOADER ---
def input_data(folder_path, sheet_name=None):
    """Loads all CSV and XLSX files from a folder, excluding specific years, and concatenates them."""
    file_paths = glob.glob(f"{folder_path}/*.xlsx") + glob.glob(f"{folder_path}/*.csv")
    df_list = []
    
    # Exclude files containing historical year strings
    exclude_strs = ["2023", "2024", "2025", "_23", "_24", "_25", " 23", " 24", " 25", "-23", "-24", "-25"]
    
    for file in file_paths:
        if any(old_year in file for old_year in exclude_strs):
            continue
            
        if file.endswith('.xlsx'):
            df = pl.read_excel(file, sheet_name=sheet_name)
        elif file.endswith('.csv'):
            try:
                df = pl.read_csv(file, encoding="utf-8")
            except Exception: # Fallback encoding if utf-8 fails
                df = pl.read_csv(file, encoding="ISO-8859-1", ignore_errors=True)
                
        # Cast all columns to string initially to avoid schema mismatch during concat
        df = df.with_columns(pl.all().cast(pl.String))
        df_list.append(df)
        
    return pl.concat(df_list, how='vertical') if df_list else pl.DataFrame()

# --- 3. LOAD & CLEAN DATA ---
# Load IEX Intervals
IEX_Intervals_Input = input_data(folder_paths["iex_intervals_output"]).with_columns([
    pl.col("OracleID").cast(pl.Int64), pl.col("IEX ID").cast(pl.Int64),
    pl.col("Week_Monday").str.to_date("%Y-%m-%d"),
    pl.col("Date_Converted").str.to_date("%Y-%m-%d"),
    pl.col("VNT_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("PST_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Datetime_Start_Time").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Datetime_End_Time").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Duration").cast(pl.Float64)
]).filter(pl.col("Date_Converted").dt.year() == 2026)

# Load RTA Agent Activity
Agent_Activity_Intervals_Input = input_data(folder_paths["rta_intervals_output"]).with_columns([
    pl.col("OracleID").cast(pl.Int64), pl.col("IEX ID").cast(pl.Int64),
    pl.col("Week_Monday").str.to_date("%Y-%m-%d"),
    pl.col("Date_Converted").str.to_date("%Y-%m-%d"),
    pl.col("VNT_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("PST_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Datetime_Start_Time").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Datetime_End_Time").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("Duration").cast(pl.Float64),
    (pl.col("Target").cast(pl.Float64) / 3600).alias("Target")
]).filter(pl.col("Date_Converted").dt.year() == 2026)

# Load Headcount Data
HC_EXTEND_COMBINED = input_data(folder_paths["hc_extend_by_month"]).filter(pl.col("Year") == "2026").select([
    pl.col("Date").str.to_date("%Y-%m-%d"),
    (pl.col("Month") + "-01").str.to_date("%b-%y-%d").dt.strftime("%y_%m").alias("Month"),
    pl.col("Email Id"), pl.col("Alias"), pl.col("Designation"), 
    pl.col("Supervisor Name"), pl.col("LOB"), pl.col("Active")
])

# Extract Scheduled Activities boundaries from IEX
IEX_Scheduled_Activities = IEX_Intervals_Input.group_by(
    ["Week_Monday", "Date_Converted", "OracleID", "IEX ID", "Employee Name", "Email Id", 'VNT_Intervals', 'PST_Intervals', 'VNT_Interval_Range', 'PST_Interval_Range']
).agg([
    pl.col("Datetime_Start_Time").filter(pl.col("Scheduled Activity").str.contains("Break")).min().alias("Scheduled_Break_Start"),
    pl.col("Datetime_Start_Time").filter(pl.col("Scheduled Activity").str.contains("Lunch")).min().alias("Scheduled_Lunch_Start"),
    pl.col("Datetime_Start_Time").filter(pl.col("Scheduled Activity").str.contains("Training|Coaching")).min().alias("Scheduled_Training_Coaching_Start"),
    pl.col("Datetime_End_Time").max().alias("Scheduled_End_Shift")
])

# Create Base Merged Data
Base_Merged_Data = IEX_Scheduled_Activities.join(
    Agent_Activity_Intervals_Input,
    on=["Week_Monday", "Date_Converted", "OracleID", "IEX ID", "Employee Name", "Email Id", "VNT_Intervals", "PST_Intervals", "VNT_Interval_Range", "PST_Interval_Range"], 
    how="left"
).join(
    HC_EXTEND_COMBINED, 
    left_on=["Date_Converted", "Email Id"], 
    right_on=["Date", "Email Id"], 
    how="left"
).drop(["Month", "LOB"]).rename({"Month_right": "Month", "LOB_right": "LOB"})

Base_Merged_Data

--- FULL FOLDER PATHS LIST ---
rta_intervals_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_ACTIVITY_INTERVALS
iex_intervals_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
output_non_compliance: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_NON_COMPLIANCE
hc_extend_by_month: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
req_path: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OU.xlsx
prod_path: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_PRODUCTIVE_REVENUE
wfm_path: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_WORKFORCE_VENDOR
------------------------------------------------------------

shape: (477_149, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Wee ┆ Dat ┆ Ora ┆ IEX ┆ Emp ┆ Ema ┆ VNT ┆ PST ┆ VNT ┆ PST ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ Age ┆ Pro ┆ Age ┆ Dat ┆ Dat ┆ Tar ┆ Dur ┆ Mon ┆ Ali ┆ Des ┆ Sup ┆ LOB ┆ Act │
│ k_M ┆ e_C ┆ cle ┆ ID  ┆ loy ┆ il  ┆ _In ┆ _In ┆ _In ┆ _In ┆ edu ┆ edu ┆ edu ┆ edu ┆ nt  ┆ duc ┆ nt  ┆ eti ┆ eti ┆ get ┆ ati ┆ th  ┆ as  ┆ ign ┆ erv ┆ --- ┆ ive │
│ ond ┆ onv ┆ ID  ┆ --- ┆ ee  ┆ Id  ┆ ter ┆ ter ┆ ter ┆ ter ┆ led ┆ led ┆ led ┆ led ┆ Que ┆ tiv ┆ Sta ┆ me_ ┆ me_ ┆ --- ┆ on  ┆ --- ┆ --- ┆ ati ┆ iso ┆ str ┆ --- │
│ ay  ┆ ert ┆ --- ┆ i64 ┆ Nam ┆ --- ┆ val ┆ val ┆ val ┆ val ┆ _Br ┆ _Lu ┆ _Tr ┆ _En ┆ ue  ┆ e   ┆ te  ┆ Sta ┆ End ┆ f64 ┆ --- ┆ str ┆ str ┆ on  ┆ r   ┆     ┆ str │
│ --- ┆ ed  ┆ i64 ┆     ┆ e   ┆ str ┆ s   ┆ s   ┆ _Ra ┆ _Ra ┆ eak ┆ nch ┆ ain ┆ d_S ┆ Gro ┆ Aux ┆ --- ┆ rt_ ┆ _Ti ┆     ┆ f64 ┆     ┆     ┆ --- ┆ Nam ┆     ┆     │
│ dat ┆ --- ┆     ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ nge ┆ nge ┆ _St ┆ _St ┆ ing ┆ hif ┆ up  ┆ Fla ┆ str ┆ Tim ┆ me  ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆     ┆     │
│ e   ┆ dat ┆     ┆     ┆ str ┆     ┆ dat ┆ dat ┆ --- ┆ --- ┆ art ┆ art ┆ _Co ┆ t   ┆ Nam ┆ g   ┆     ┆ e   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆ e   ┆     ┆     ┆     ┆     ┆ eti ┆ eti ┆ str ┆ str ┆ --- ┆ --- ┆ ach ┆ --- ┆ e   ┆ (Ye ┆     ┆ --- ┆ dat ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ me[ ┆     ┆     ┆ dat ┆ dat ┆ ing ┆ dat ┆ --- ┆ s / ┆     ┆ dat ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆ μs] ┆     ┆     ┆ eti ┆ eti ┆ _St ┆ eti ┆ str ┆ No) ┆     ┆ eti ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ me[ ┆ …   ┆ me[ ┆     ┆ --- ┆     ┆ me[ ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆ μs] ┆ --- ┆ μs] ┆     ┆ str ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 103 ┆ 310 ┆ BUI ┆ ngo ┆ 202 ┆ 202 ┆ 23: ┆ 09: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Lun ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.5 ┆ 26_ ┆ Mim ┆ Adv ┆ Tru ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 293 ┆ 939 ┆ NGO ┆ cth ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ch  ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 04  ┆ i   ┆ iso ┆ ong ┆ gin ┆     │
│ 4-0 ┆ 4-1 ┆ 751 ┆ 4   ┆ C   ┆ uan ┆ 4-1 ┆ 4-1 ┆ 00: ┆ 10: ┆     ┆ 4-1 ┆     ┆ 4-1 ┆ D_E ┆     ┆     ┆ 4-1 ┆ 4-1 ┆     ┆     ┆     ┆     ┆ r   ┆ Thi ┆ g   ┆     │
│ 6   ┆ 0   ┆     ┆     ┆ THU ┆ vy. ┆ 0   ┆ 0   ┆ 00  ┆ 00  ┆     ┆ 0   ┆     ┆ 1   ┆ N_C ┆     ┆     ┆ 0   ┆ 1   ┆     ┆     ┆     ┆     ┆ I,  ┆ en  ┆     ┆     │
│     ┆     ┆     ┆     ┆ AN  ┆ bui ┆ 23: ┆ 09: ┆     ┆     ┆     ┆ 23: ┆     ┆ 00: ┆ ar_ ┆     ┆     ┆ 23: ┆ 00: ┆     ┆     ┆     ┆     ┆ Cus ┆ Tha ┆     ┆     │
│     ┆     ┆     ┆     ┆ VY  ┆ @co ┆ 30: ┆ 30: ┆     ┆     ┆     ┆ 30: ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 30: ┆ 00: ┆     ┆     ┆     ┆     ┆ tom ┆ nh  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆ er  ┆ Toa ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆ n   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.2 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 691 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 13: ┆ 30: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 51  ┆ 00  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.1 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 566 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 04: ┆ 13: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 27  ┆ 51  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.0 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 741 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 00: ┆ 04: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 27  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ HUY ┆ qua ┆ 202 ┆ 202 ┆ 02: ┆ 11: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 26_ ┆ Jas ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 169 ┆ 663 ┆ NH  ┆ nga ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 01  ┆ on  ┆ iso ┆ n   ┆ gin ┆     │
│ 1-1 ┆ 1-1 ┆ 795 ┆ 7   ┆ QUA ┆ nh. ┆ 1-1 ┆ 1-1 ┆ 03: ┆ 12: ┆     ┆     ┆     ┆ 1-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 2   ┆ 4   ┆     ┆     ┆ NG  ┆ huy ┆ 5   ┆ 4   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ ANH ┆ nh@ ┆ 02: ┆ 11: ┆     ┆     ┆     ┆     ┆     ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ con ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ cen ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ x.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ om  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.0 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 841 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 67  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 30: ┆ 35: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 03  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.0 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 038 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 89  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 49: ┆ 50: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 56  ┆ 10  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.1 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 313 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 89  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 35: ┆ 42: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 03  ┆ 56  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.1 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 155 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 56  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 43: ┆ 49: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 56  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 102 ┆ 301 ┆ NGO ┆ van ┆ 202 ┆ 202 ┆ 03: ┆ 13: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 26_ ┆ Dal ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 864 ┆ 481 ┆ VAN ┆ min ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 04  ┆ an  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-2 ┆ 4-2 ┆ 715 ┆ 7   ┆ MIN ┆ hdu ┆ 4-2 ┆ 4-2 ┆ 04: ┆ 14: ┆     ┆     ┆     ┆ 4-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 0   ┆ 3   ┆     ┆     ┆ H   ┆ y.n ┆ 4   ┆ 3   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ DUY ┆ go@ ┆ 03: ┆ 13: ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ con ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ cen ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │

In [62]:
# --- AVOIDANCE CALCULATION ---
avoiding_states = ["Break", "Lunch", "Training", "Coaching", 'Team Meeting', 'End of Shift']

# 1. Sort and calculate daily boundaries & total productive minutes
df_sorted = Base_Merged_Data.sort(["Email Id", "Date_Converted", "Datetime_Start_Time"]).with_columns([
    pl.col("Scheduled_End_Shift").max().over(["Email Id", "Date_Converted"]).alias("Daily_End_Shift"),
    (
        pl.col("Duration")
        .filter(pl.col("Productive Aux Flag (Yes / No)") == "Yes")
        .sum()
        .over(["Email Id", "Date_Converted"]) * 60
    ).round(2).alias("Total_Available_Mins")
])

# 2. Flag Exemptions & Violations
df_flagged = df_sorted.with_columns([
    # Check if the state matches the scheduled time
    (
        ((pl.col("Agent State") == "Break") & pl.col("Scheduled_Break_Start").is_not_null()) |
        ((pl.col("Agent State") == "Lunch") & pl.col("Scheduled_Lunch_Start").is_not_null()) |
        (pl.col("Agent State").is_in(["Training", "Coaching", "Team Meeting"]) & pl.col("Scheduled_Training_Coaching_Start").is_not_null()) |
        ((pl.col("Agent State") == "End of Shift") & pl.col("Scheduled_End_Shift").is_not_null()) |
        ((pl.col("Agent State") == "End of Shift") & pl.col("Daily_End_Shift").is_not_null() & (pl.col("Datetime_Start_Time") >= pl.col("Daily_End_Shift")))
    ).alias("Is_Scheduled_Exempt"),
    
    # Start Violation: Unproductive state followed by Productive state
    (
        (pl.col("Agent State").is_in(avoiding_states)) & (pl.col("Productive Aux Flag (Yes / No)") == "Yes") &
        (pl.col("Agent State").shift(-1).over(["Email Id", "Date_Converted"]).is_in(["Available Chat", "Outbound Call"])) &
        (pl.col("Productive Aux Flag (Yes / No)").shift(-1).over(["Email Id", "Date_Converted"]) == "Yes")
    ).alias("Is_Start_Violation"),
    
    # End Violation: Productive state preceded by Unproductive state
    (
        (pl.col("Agent State").is_in(["Available Chat", "Outbound Call"])) & (pl.col("Productive Aux Flag (Yes / No)") == "Yes") &
        (pl.col("Agent State").shift(1).over(["Email Id", "Date_Converted"]).is_in(avoiding_states)) &
        (pl.col("Productive Aux Flag (Yes / No)").shift(1).over(["Email Id", "Date_Converted"]) == "Yes")
    ).alias("Is_End_Violation")
]).with_columns(
    # Create violation groups for aggregating durations
    pl.col("Is_Start_Violation").cast(pl.Int32).cum_sum().over(["Email Id", "Date_Converted"]).alias("Violation_Group")
)

# 3. Aggregate Violations and finalize dataset
Agent_Avoidance_RawData = df_flagged.filter(pl.col("Is_Start_Violation") | pl.col("Is_End_Violation")).with_columns([
    pl.col("Datetime_Start_Time").min().over(["Email Id", "Date_Converted", "Violation_Group"]).alias("Event_Start_Time"),
    pl.col("Datetime_End_Time").max().over(["Email Id", "Date_Converted", "Violation_Group"]).alias("Event_End_Time")
]).with_columns([
    (pl.col("Event_End_Time") - pl.col("Event_Start_Time")).dt.total_seconds().alias("Duration_Secs")
]).with_columns([
    pl.col("Is_Scheduled_Exempt").any().over(["Email Id", "Date_Converted", "Violation_Group"]).alias("Group_Is_Scheduled"),
    (pl.col("Is_Start_Violation") & (pl.col("Duration_Secs") < 60)).any().over(["Email Id", "Date_Converted", "Violation_Group"]).alias("Group_Is_Short")
]).with_columns([
    # Assign exemption reason
    pl.when(pl.col("Group_Is_Scheduled") & pl.col("Group_Is_Short")).then(pl.lit("Scheduled activity & Duration < 60s"))
    .when(pl.col("Group_Is_Scheduled")).then(pl.lit("Scheduled activity"))
    .when(pl.col("Group_Is_Short")).then(pl.lit("Duration < 60s"))
    .otherwise(pl.lit(None)).alias("Exemption_Reason")
]).with_columns([
    # Final Flags and Formatting
    pl.when(pl.col("Exemption_Reason").is_not_null()).then(pl.lit("No")).otherwise(pl.lit("Yes")).alias("Non_Compliance"),
    pl.concat_str([
        pl.col("Date_Converted").cast(pl.String), pl.lit("_"), pl.col("Email Id"), pl.lit("_"),
        pl.col("Event_Start_Time").dt.strftime("%H%M%S"), pl.lit("-"), pl.col("Event_End_Time").dt.strftime("%H%M%S")
    ]).alias("Non_Compliance_Code"),
    pl.when(pl.col("Agent State").is_in(["Break", "Lunch", "Training", "Coaching", "Team Meeting"]))
    .then((pl.col("Duration_Secs") / 60.0).round(2))
    .otherwise(None).alias("Duration_Mins") 
]).select([
    "Month", "Date_Converted", "Email Id", "Employee Name", "LOB", "Alias", "Designation", "Supervisor Name", "Active",
    "VNT_Intervals", "Datetime_Start_Time", "Datetime_End_Time", 
    "Duration_Mins", "Total_Available_Mins", "Agent State", "Productive Aux Flag (Yes / No)", 
    "Scheduled_Break_Start", "Scheduled_Lunch_Start", "Scheduled_Training_Coaching_Start", "Scheduled_End_Shift", 
    "Non_Compliance", "Exemption_Reason", "Non_Compliance_Code"
]).rename({
    "Date_Converted": "Date",
    "Datetime_Start_Time": "State_Start_Time",
    "Datetime_End_Time": "State_End_Time",
    "Duration_Mins": "Avoidance_Duration_Mins", 
    "Productive Aux Flag (Yes / No)": "Is_Productive_Aux",
    "Non_Compliance": "Is_Avoidance_Violation"
})

In [63]:
# --- SCHEDULE ADHERENCE GAP ---
groupby_cols = ["Month", "Week_Monday", "Date_Converted", "Alias", "LOB", "Designation", "Supervisor Name", "Active", "Employee Name", "Email Id", "OracleID", "IEX ID", "VNT_Intervals", "PST_Intervals", "VNT_Interval_Range", "PST_Interval_Range"]

# 1. Aggregate Actual RTA Data
Agent_Activity_Adherence = Base_Merged_Data.group_by(groupby_cols).agg([
    # Break
    pl.col("Datetime_Start_Time").filter(pl.col("Agent State").str.contains("Break") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).min().alias("Actual_Break_Start"),
    pl.col("Datetime_End_Time").filter(pl.col("Agent State").str.contains("Break") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).max().alias("Actual_Break_End"),
    (pl.col("Duration").filter(pl.col("Agent State").str.contains("Break") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).sum() * 60).round(2).alias("Actual_Break_Duration"),
    
    # Lunch
    pl.col("Datetime_Start_Time").filter(pl.col("Agent State").str.contains("Lunch") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).min().alias("Actual_Lunch_Start"),
    pl.col("Datetime_End_Time").filter(pl.col("Agent State").str.contains("Lunch") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).max().alias("Actual_Lunch_End"),
    (pl.col("Duration").filter(pl.col("Agent State").str.contains("Lunch") & (pl.col("Productive Aux Flag (Yes / No)") == "No")).sum() * 60).round(2).alias("Actual_Lunch_Duration"),
    
    # Training / Coaching
    pl.col("Datetime_Start_Time").filter(pl.col("Agent State").is_in(['Team Meeting', 'Coaching', 'Training']) & (pl.col("Productive Aux Flag (Yes / No)") == "No")).min().alias("Actual_TC_Start"),
    pl.col("Datetime_End_Time").filter(pl.col("Agent State").is_in(['Team Meeting', 'Coaching', 'Training']) & (pl.col("Productive Aux Flag (Yes / No)") == "No")).max().alias("Actual_TC_End"),
    (pl.col("Duration").filter(pl.col("Agent State").is_in(['Team Meeting', 'Coaching', 'Training']) & (pl.col("Productive Aux Flag (Yes / No)") == "No")).sum() * 60).round(2).alias("Actual_TC_Duration")
])

# 2. Aggregate Scheduled IEX Data
IEX_Adherence = IEX_Intervals_Input.group_by(["Date_Converted", "Email Id", "VNT_Intervals"]).agg([
    pl.col("Datetime_Start_Time").min().alias("Scheduled_Start"),
    pl.col("Datetime_End_Time").max().alias("Scheduled_End"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Break")).sum() * 60).round(2).alias("Scheduled_Break_Duration"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Lunch")).sum() * 60).round(2).alias("Scheduled_Lunch_Duration"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Training|Coaching")).sum() * 60).round(2).alias("Scheduled_TC_Duration")
])

# 3. Join and calculate Gaps (Actual - Scheduled -> Positive = Over, Negative = Under)
Merged_Adherence = Agent_Activity_Adherence.join(IEX_Adherence, on=["Date_Converted", "Email Id", "VNT_Intervals"], how="left").with_columns([
    (pl.col("Actual_Break_Duration").fill_null(0) - pl.col("Scheduled_Break_Duration").fill_null(0)).alias("Gap_Break"),
    (pl.col("Actual_Lunch_Duration").fill_null(0) - pl.col("Scheduled_Lunch_Duration").fill_null(0)).alias("Gap_Lunch"),
    (pl.col("Actual_TC_Duration").fill_null(0) - pl.col("Scheduled_TC_Duration").fill_null(0)).alias("Gap_TC")
])

# 4. Unpivot / Restructure data by Activity Type
df_break = Merged_Adherence.select(groupby_cols + [
    pl.lit("Break").alias("Activity_Type"), pl.col("Actual_Break_Start").alias("Actual_Start_Time"), pl.col("Actual_Break_End").alias("Actual_End_Time"),
    pl.col("Scheduled_Start"), pl.col("Scheduled_End"), pl.col("Scheduled_Break_Duration").alias("Scheduled_Duration"),
    pl.col("Actual_Break_Duration").alias("Actual_Duration"), pl.col("Gap_Break").alias("Gap")
])

df_lunch = Merged_Adherence.select(groupby_cols + [
    pl.lit("Lunch").alias("Activity_Type"), pl.col("Actual_Lunch_Start").alias("Actual_Start_Time"), pl.col("Actual_Lunch_End").alias("Actual_End_Time"),
    pl.col("Scheduled_Start"), pl.col("Scheduled_End"), pl.col("Scheduled_Lunch_Duration").alias("Scheduled_Duration"),
    pl.col("Actual_Lunch_Duration").alias("Actual_Duration"), pl.col("Gap_Lunch").alias("Gap")
])

df_tc = Merged_Adherence.select(groupby_cols + [
    pl.lit("Training | Coaching").alias("Activity_Type"), pl.col("Actual_TC_Start").alias("Actual_Start_Time"), pl.col("Actual_TC_End").alias("Actual_End_Time"),
    pl.col("Scheduled_Start"), pl.col("Scheduled_End"), pl.col("Scheduled_TC_Duration").alias("Scheduled_Duration"),
    pl.col("Actual_TC_Duration").alias("Actual_Duration"), pl.col("Gap_TC").alias("Gap")
])

# 5. Final Formatting and Tolerance Status assignment
Schedule_Adherence_Gap = pl.concat([df_break, df_lunch, df_tc]).filter(
    (pl.col("Scheduled_Duration").fill_null(0) > 0) | (pl.col("Actual_Duration").fill_null(0) > 0)
).sort(["Email Id", "Date_Converted", "VNT_Intervals", "Activity_Type"]).rename({
    "Date_Converted": "Date",
    "Actual_Start_Time": "Actual_Activity_Start",
    "Actual_End_Time": "Actual_Activity_End",
    "Scheduled_Start": "Scheduled_Activity_Start",
    "Scheduled_End": "Scheduled_Activity_End",
    "Actual_Duration": "Actual_Duration_Mins",
    "Scheduled_Duration": "Scheduled_Duration_Mins",
    "Gap": "Duration_Gap_Mins"
}).with_columns(
    # Set status using a +/- 2 minute tolerance for 'Matched'
    pl.when(pl.col("Duration_Gap_Mins") > 2).then(pl.lit("Over Scheduled"))
    .when(pl.col("Duration_Gap_Mins") < -2).then(pl.lit("Under Scheduled"))
    .otherwise(pl.lit("Matched"))
    .alias("Gap_Status")
)

In [64]:
# --- AGENT REST COMPLIANCE ---
actual_rest_raw = Base_Merged_Data.filter(
    pl.col("Agent State").is_in(["Break", "Lunch"])
).sort(["Email Id", "Date_Converted", "Datetime_Start_Time"])

# 1. Identify distinct Rest Sessions (state change OR gap > 60s)
actual_rest_raw = actual_rest_raw.with_columns(
    (
        (pl.col("Agent State") != pl.col("Agent State").shift(1).over(["Email Id", "Date_Converted"])) |
        ((pl.col("Datetime_Start_Time") - pl.col("Datetime_End_Time").shift(1).over(["Email Id", "Date_Converted"])).dt.total_seconds() > 60)
    ).fill_null(True).alias("Is_New_Session")
).with_columns(
    pl.col("Is_New_Session").cast(pl.Int32).cum_sum().over(["Email Id", "Date_Converted"]).alias("Session_ID")
)

# 2. Aggregate sessions and remove micro-sessions (< 1 min)
Agent_Rest_Compliance_Log = actual_rest_raw.group_by([
    "Month", "Date_Converted", "Email Id", "Employee Name", "Alias", "LOB", "Designation", "Supervisor Name", "Active", "Agent State", "Session_ID"
]).agg([
    pl.col("Datetime_Start_Time").min().alias("Session_Start_Time"),
    pl.col("Datetime_End_Time").max().alias("Session_End_Time"),
    (pl.col("Duration").filter(pl.col("Productive Aux Flag (Yes / No)") == "No").sum() * 60).round(2).alias("Total_Duration_Mins") 
]).sort(["Email Id", "Date_Converted", "Session_Start_Time"]).filter(
    pl.col("Total_Duration_Mins").fill_null(0) >= 1.0
)

# 3. Apply limit logic and bucket exceptions
Agent_Rest_Compliance_Log = Agent_Rest_Compliance_Log.with_columns(
    pl.col("Session_Start_Time").rank("ordinal").over(["Email Id", "Date_Converted", "Agent State"]).alias("Rank")
).with_columns(
    # Name the session dynamically (e.g., Break_1, Lunch_1)
    pl.when(pl.col("Agent State") == "Break").then(pl.lit("Break_") + pl.col("Rank").cast(pl.String))
    .when((pl.col("Agent State") == "Lunch") & (pl.col("Rank") == 1)).then(pl.lit("Lunch"))
    .otherwise(pl.lit("Lunch_") + pl.col("Rank").cast(pl.String)).alias("Detail_Rest_Type")
).with_columns([
    # Flag over rest (Break limit: 15m, Lunch limit: 60m)
    pl.when((pl.col("Agent State") == "Break") & (pl.col("Total_Duration_Mins") > 15.0)).then(pl.lit("Yes (>15m)"))
    .when((pl.col("Agent State") == "Lunch") & (pl.col("Total_Duration_Mins") > 60.0)).then(pl.lit("Yes (>60m)"))
    .otherwise(pl.lit("No")).alias("Is_Over_Rest"),
    
    # Calculate excess duration
    pl.when((pl.col("Agent State") == "Break") & (pl.col("Total_Duration_Mins") > 15.0)).then((pl.col("Total_Duration_Mins") - 15.0).round(2))
    .when((pl.col("Agent State") == "Lunch") & (pl.col("Total_Duration_Mins") > 60.0)).then((pl.col("Total_Duration_Mins") - 60.0).round(2))
    .otherwise(pl.lit(0.0)).alias("Over_Duration_Mins")
]).select([
    "Month", "Date_Converted", "Email Id", "Employee Name", "Alias", "LOB", "Designation", "Supervisor Name", "Active", 
    "Detail_Rest_Type", "Session_Start_Time", "Session_End_Time", "Total_Duration_Mins", 
    "Is_Over_Rest", "Over_Duration_Mins"
]).rename({
    "Date_Converted": "Date",
    "Detail_Rest_Type": "Rest_Session_Name",
    "Total_Duration_Mins": "Actual_Rest_Duration_Mins",
    "Is_Over_Rest": "Is_Exceeding_Limit",
    "Over_Duration_Mins": "Exceeded_By_Mins"
}).with_columns(
    # Bucket the exceeded time
    pl.when(pl.col("Exceeded_By_Mins") > 10).then(pl.lit("> 10 min"))
    .when(pl.col("Exceeded_By_Mins") > 5).then(pl.lit("5-10 min"))
    .when(pl.col("Exceeded_By_Mins") >= 1).then(pl.lit("1-5 min"))
    .when(pl.col("Exceeded_By_Mins") > 0).then(pl.lit("< 1 min"))
    .otherwise(pl.lit("Not Exceeded"))
    .alias("Exceed_Bucket")
)

In [65]:
# --- INTERVAL COMPLIANCE & MERGING ---
lob_mapping = {
    "GEN_GEN_EN_GCS_GLG_CHT": "Lodging chat",
    "GEN_GEN_EN_GCS_GNL_CHT": "Non-Lodging chat",
    "GEN_GEN_EN_GCS_GLG_CHT_Concentrix": "Lodging chat",
    "GEN_GEN_EN_GCS_GNL_CHT_Concentrix": "Non-Lodging chat"
}

vnt_tz_expr = (
    pl.col("PST_Intervals")
    .dt.replace_time_zone("America/Los_Angeles", non_existent="null", ambiguous="earliest")
    .dt.convert_time_zone("Asia/Ho_Chi_Minh")
    .dt.replace_time_zone(None)
    .alias("VNT_Intervals")
)

# 1. Process Required Heads (OU_Data)
OU_Data = pl.read_excel(folder_paths["req_path"], has_header=False)
new_headers = [str(val) for val in OU_Data.row(0)]
rename_mapping = dict(zip(OU_Data.columns, new_headers))

OU_Data = OU_Data.slice(1).rename(rename_mapping).unpivot(
    index=["LOB", "Site", "Interval"], variable_name="Date", value_name="Req"
).with_columns([
    pl.col("Date").str.slice(0, 10).str.to_date("%Y-%m-%d"),
    pl.col("Interval").str.to_datetime("%Y-%m-%d %H:%M:%S", strict=False).dt.time(),
    pl.col("Req").cast(pl.Float64, strict=False)
]).with_columns(
    pl.col("Date").dt.combine(pl.col("Interval")).alias("PST_Intervals")
).with_columns(vnt_tz_expr)

# 2. Process Revenue / Productive Data
Productive_Revenue_Data = input_data(folder_paths["prod_path"]).with_columns([
    pl.col("Productive Hours (Sum)").cast(pl.Float64, strict=False),
    pl.col("Productive Idle Hour (Sum)").cast(pl.Float64, strict=False),
    pl.col("Handle Count (Sum)").cast(pl.Float64, strict=False)
]).group_by(["Business Location", "Interval", "Forecast Group Name"]).agg([
    pl.col("Productive Hours (Sum)").sum(),
    pl.col("Productive Idle Hour (Sum)").sum(),
    pl.col("Handle Count (Sum)").sum()
]).rename({
    "Business Location": "Site", "Forecast Group Name": "LOB", "Interval": "PST_Intervals"
}).with_columns([
    pl.col("LOB").replace_strict(lob_mapping, default=pl.col("LOB")),
    pl.col("PST_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S", strict=False),
    pl.when(pl.col("Productive Hours (Sum)") == 0).then(None).otherwise(
        (pl.col("Productive Hours (Sum)") - pl.col("Productive Idle Hour (Sum)")) / pl.col("Productive Hours (Sum)")
    ).alias("Occupancy_Site_Level")
]).with_columns(vnt_tz_expr)

# 3. Process Workforce Vendor Data
vendor_cols = ["Forecast Productive Hour (Sum)", "Productive Hour (Sum)", "Staffing Attainment (Pct)", "Interval Compliance (Pct)", "Occupancy", "Billable Hours (Sum)"]

Workforce_Vendor_Data = input_data(folder_paths["wfm_path"]).with_columns(
    [pl.col(c).cast(pl.Float64, strict=False) for c in vendor_cols]
).group_by(["Vendor Forecast Group Name", "Interval Time"]).agg(
    [pl.col(c).sum() for c in vendor_cols]
).rename({
    "Vendor Forecast Group Name": "LOB", "Interval Time": "PST_Intervals"
}).with_columns([
    pl.col("LOB").replace_strict(lob_mapping, default=pl.col("LOB")),
    pl.col("PST_Intervals").str.to_datetime("%Y-%m-%d %H:%M:%S", strict=False),
    pl.when(pl.col("Interval Compliance (Pct)") >= 1).then(pl.lit("Met")).otherwise(pl.lit("Missed")).alias("IC Status")
]).with_columns(vnt_tz_expr)

# 4. Final Data Merging with renamed productive columns
revenue_subset = Productive_Revenue_Data.select([
    "LOB", "PST_Intervals", "Site", 
    pl.col("Productive Hours (Sum)").alias("Site_Productive_Hours"), # Rename HCM Site productive
    "Handle Count (Sum)", "Occupancy_Site_Level"
])

ou_subset = OU_Data.select(["LOB", "Site", "PST_Intervals", "Req"])

Final_Merged_Data = Workforce_Vendor_Data.rename({
    "Productive Hour (Sum)": "Total_LOB_Productive_Hours" # Rename Global/Vendor productive
}).join(
    revenue_subset, on=["LOB", "PST_Intervals"], how="left", suffix="_Site_Level"
).join(
    ou_subset, on=["LOB", "Site", "PST_Intervals"], how="left"
).rename(
    {"Req": "Req_Site_Level"}
).with_columns([
    # Calculation using new names
    pl.when(pl.col("Req_Site_Level") == 0).then(None).otherwise(
        pl.col("Site_Productive_Hours") / pl.col("Req_Site_Level")
    ).alias("Staffing Attainment (Pct)_Site_Level"),
    
    (pl.col("Forecast Productive Hour (Sum)") * 2).alias("Forecast Heads"),
    (pl.col("Total_LOB_Productive_Hours") * 2).alias("Actual Heads"), # Renamed reference
    (pl.col("Site_Productive_Hours") * 2).alias("Site Actual Heads"), # Renamed reference
    (pl.col("Req_Site_Level") * 2).alias("Site Req Heads"),
    
    # Date/Time formatting
    pl.col("PST_Intervals").dt.strftime("%Y-%m").alias("PST_Month"),
    pl.col("PST_Intervals").dt.date().alias("PST_Date"),
    pl.concat_str([
        pl.col("PST_Intervals").dt.strftime("%H:%M"), pl.lit("-"),
        (pl.col("PST_Intervals") + pl.duration(minutes=30)).dt.strftime("%H:%M")
    ]).alias("PST_Interval_Range"),
    
    pl.col("VNT_Intervals").dt.date().alias("VNT_Date"),
    pl.concat_str([
        pl.col("VNT_Intervals").dt.strftime("%H:%M"), pl.lit("-"),
        (pl.col("VNT_Intervals") + pl.duration(minutes=30)).dt.strftime("%H:%M")
    ]).alias("VNT_Interval_Range")
]).select([
    "LOB", "PST_Month", "PST_Date", "PST_Intervals", "PST_Interval_Range",
    "VNT_Date", "VNT_Intervals", "VNT_Interval_Range",
    "Forecast Productive Hour (Sum)", "Forecast Heads", 
    "Total_LOB_Productive_Hours", "Actual Heads", # New Names
    "Staffing Attainment (Pct)", "Interval Compliance (Pct)", "IC Status", "Occupancy", "Billable Hours (Sum)",
    "Site", "Req_Site_Level", "Site Req Heads", 
    "Site_Productive_Hours", "Site Actual Heads", # New Names
    "Staffing Attainment (Pct)_Site_Level", "Occupancy_Site_Level", "Handle Count (Sum)"
])

In [66]:
Base_Merged_Data

shape: (477_149, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Wee ┆ Dat ┆ Ora ┆ IEX ┆ Emp ┆ Ema ┆ VNT ┆ PST ┆ VNT ┆ PST ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ Age ┆ Pro ┆ Age ┆ Dat ┆ Dat ┆ Tar ┆ Dur ┆ Mon ┆ Ali ┆ Des ┆ Sup ┆ LOB ┆ Act │
│ k_M ┆ e_C ┆ cle ┆ ID  ┆ loy ┆ il  ┆ _In ┆ _In ┆ _In ┆ _In ┆ edu ┆ edu ┆ edu ┆ edu ┆ nt  ┆ duc ┆ nt  ┆ eti ┆ eti ┆ get ┆ ati ┆ th  ┆ as  ┆ ign ┆ erv ┆ --- ┆ ive │
│ ond ┆ onv ┆ ID  ┆ --- ┆ ee  ┆ Id  ┆ ter ┆ ter ┆ ter ┆ ter ┆ led ┆ led ┆ led ┆ led ┆ Que ┆ tiv ┆ Sta ┆ me_ ┆ me_ ┆ --- ┆ on  ┆ --- ┆ --- ┆ ati ┆ iso ┆ str ┆ --- │
│ ay  ┆ ert ┆ --- ┆ i64 ┆ Nam ┆ --- ┆ val ┆ val ┆ val ┆ val ┆ _Br ┆ _Lu ┆ _Tr ┆ _En ┆ ue  ┆ e   ┆ te  ┆ Sta ┆ End ┆ f64 ┆ --- ┆ str ┆ str ┆ on  ┆ r   ┆     ┆ str │
│ --- ┆ ed  ┆ i64 ┆     ┆ e   ┆ str ┆ s   ┆ s   ┆ _Ra ┆ _Ra ┆ eak ┆ nch ┆ ain ┆ d_S ┆ Gro ┆ Aux ┆ --- ┆ rt_ ┆ _Ti ┆     ┆ f64 ┆     ┆     ┆ --- ┆ Nam ┆     ┆     │
│ dat ┆ --- ┆     ┆     ┆ --- ┆     ┆ --- ┆ --- ┆ nge ┆ nge ┆ _St ┆ _St ┆ ing ┆ hif ┆ up  ┆ Fla ┆ str ┆ Tim ┆ me  ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆     ┆     │
│ e   ┆ dat ┆     ┆     ┆ str ┆     ┆ dat ┆ dat ┆ --- ┆ --- ┆ art ┆ art ┆ _Co ┆ t   ┆ Nam ┆ g   ┆     ┆ e   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆ e   ┆     ┆     ┆     ┆     ┆ eti ┆ eti ┆ str ┆ str ┆ --- ┆ --- ┆ ach ┆ --- ┆ e   ┆ (Ye ┆     ┆ --- ┆ dat ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ me[ ┆     ┆     ┆ dat ┆ dat ┆ ing ┆ dat ┆ --- ┆ s / ┆     ┆ dat ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆ μs] ┆     ┆     ┆ eti ┆ eti ┆ _St ┆ eti ┆ str ┆ No) ┆     ┆ eti ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ me[ ┆ …   ┆ me[ ┆     ┆ --- ┆     ┆ me[ ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆ μs] ┆ --- ┆ μs] ┆     ┆ str ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 103 ┆ 310 ┆ BUI ┆ ngo ┆ 202 ┆ 202 ┆ 23: ┆ 09: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Lun ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.5 ┆ 26_ ┆ Mim ┆ Adv ┆ Tru ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 293 ┆ 939 ┆ NGO ┆ cth ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ch  ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 04  ┆ i   ┆ iso ┆ ong ┆ gin ┆     │
│ 4-0 ┆ 4-1 ┆ 751 ┆ 4   ┆ C   ┆ uan ┆ 4-1 ┆ 4-1 ┆ 00: ┆ 10: ┆     ┆ 4-1 ┆     ┆ 4-1 ┆ D_E ┆     ┆     ┆ 4-1 ┆ 4-1 ┆     ┆     ┆     ┆     ┆ r   ┆ Thi ┆ g   ┆     │
│ 6   ┆ 0   ┆     ┆     ┆ THU ┆ vy. ┆ 0   ┆ 0   ┆ 00  ┆ 00  ┆     ┆ 0   ┆     ┆ 1   ┆ N_C ┆     ┆     ┆ 0   ┆ 1   ┆     ┆     ┆     ┆     ┆ I,  ┆ en  ┆     ┆     │
│     ┆     ┆     ┆     ┆ AN  ┆ bui ┆ 23: ┆ 09: ┆     ┆     ┆     ┆ 23: ┆     ┆ 00: ┆ ar_ ┆     ┆     ┆ 23: ┆ 00: ┆     ┆     ┆     ┆     ┆ Cus ┆ Tha ┆     ┆     │
│     ┆     ┆     ┆     ┆ VY  ┆ @co ┆ 30: ┆ 30: ┆     ┆     ┆     ┆ 30: ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 30: ┆ 00: ┆     ┆     ┆     ┆     ┆ tom ┆ nh  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆ er  ┆ Toa ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆ n   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.2 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 691 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 13: ┆ 30: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 51  ┆ 00  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.1 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 566 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 04: ┆ 13: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 27  ┆ 51  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ TRA ┆ thi ┆ 202 ┆ 202 ┆ 11: ┆ 20: ┆ nul ┆ 202 ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 9.5 ┆ 0.0 ┆ 26_ ┆ Jad ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 171 ┆ 679 ┆ N   ┆ bic ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 00- ┆ l   ┆ 6-0 ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆ 666 ┆ 741 ┆ 01  ┆ eli ┆ iso ┆ n   ┆ gin ┆     │
│ 1-0 ┆ 1-0 ┆ 103 ┆ 8   ┆ THI ┆ hlo ┆ 1-0 ┆ 1-0 ┆ 11: ┆ 20: ┆     ┆ 1-0 ┆     ┆ 1-0 ┆ D_E ┆     ┆ ble ┆ 1-0 ┆ 1-0 ┆ 67  ┆ 67  ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 5   ┆ 7   ┆     ┆     ┆ BIC ┆ i.t ┆ 7   ┆ 6   ┆ 30  ┆ 30  ┆     ┆ 7   ┆     ┆ 7   ┆ N_C ┆     ┆ Cha ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ H   ┆ ran ┆ 11: ┆ 20: ┆     ┆     ┆     ┆ 11: ┆     ┆ 11: ┆ ar_ ┆     ┆ t   ┆ 11: ┆ 11: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LOI ┆ @co ┆ 00: ┆ 00: ┆     ┆     ┆     ┆ 15: ┆     ┆ 30: ┆ Act ┆     ┆     ┆ 00: ┆ 04: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 00  ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 27  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 309 ┆ HUY ┆ qua ┆ 202 ┆ 202 ┆ 02: ┆ 11: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 26_ ┆ Jas ┆ Adv ┆ Tra ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 169 ┆ 663 ┆ NH  ┆ nga ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 01  ┆ on  ┆ iso ┆ n   ┆ gin ┆     │
│ 1-1 ┆ 1-1 ┆ 795 ┆ 7   ┆ QUA ┆ nh. ┆ 1-1 ┆ 1-1 ┆ 03: ┆ 12: ┆     ┆     ┆     ┆ 1-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆ Sha ┆ g   ┆     │
│ 2   ┆ 4   ┆     ┆     ┆ NG  ┆ huy ┆ 5   ┆ 4   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I,  ┆ ron ┆     ┆     │
│     ┆     ┆     ┆     ┆ ANH ┆ nh@ ┆ 02: ┆ 11: ┆     ┆     ┆     ┆     ┆     ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ con ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ cen ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ x.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ om  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.0 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 841 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 67  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 30: ┆ 35: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 03  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.0 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 038 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 89  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 49: ┆ 50: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 56  ┆ 10  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.1 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 313 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 89  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 35: ┆ 42: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 03  ┆ 56  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 103 ┆ 305 ┆ TO  ┆ ngu ┆ 202 ┆ 202 ┆ 20: ┆ 06: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ Cha ┆ Yes ┆ Ava ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.1 ┆ 26_ ┆ Dra ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 060 ┆ 218 ┆ NGU ┆ yen ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ t_O ┆     ┆ ila ┆ 6-0 ┆ 6-0 ┆     ┆ 155 ┆ 04  ┆ ke  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-1 ┆ 4-1 ┆ 430 ┆ 7   ┆ YEN ┆ hoa ┆ 4-1 ┆ 4-1 ┆ 21: ┆ 07: ┆     ┆     ┆     ┆ 4-1 ┆ D_E ┆     ┆ ble ┆ 4-1 ┆ 4-1 ┆     ┆ 56  ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 3   ┆ 5   ┆     ┆     ┆ HOA ┆ ngl ┆ 5   ┆ 5   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 5   ┆ N_C ┆     ┆ Cha ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ NG  ┆ ong ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆ 21: ┆ ar_ ┆     ┆ t   ┆ 20: ┆ 20: ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ LON ┆ .to ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ Act ┆     ┆     ┆ 43: ┆ 49: ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ G   ┆ @co ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ ivi ┆     ┆     ┆ 00  ┆ 56  ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vic ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ix. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 102 ┆ 301 ┆ NGO ┆ van ┆ 202 ┆ 202 ┆ 03: ┆ 13: ┆ nul ┆ nul ┆ nul ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 26_ ┆ Dal ┆ Adv ┆ Mia ┆ Lod ┆ Yes │
│ 6-0 ┆ 6-0 ┆ 864 ┆ 481 ┆ VAN ┆ min ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 30- ┆ l   ┆ l   ┆ l   ┆ 6-0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 04  ┆ an  ┆ iso ┆ Min ┆ gin ┆     │
│ 4-2 ┆ 4-2 ┆ 715 ┆ 7   ┆ MIN ┆ hdu ┆ 4-2 ┆ 4-2 ┆ 04: ┆ 14: ┆     ┆     ┆     ┆ 4-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆ h   ┆ g   ┆     │
│ 0   ┆ 3   ┆     ┆     ┆ H   ┆ y.n ┆ 4   ┆ 3   ┆ 00  ┆ 00  ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I,  ┆ Lê  ┆     ┆     │
│     ┆     ┆     ┆     ┆ DUY ┆ go@ ┆ 03: ┆ 13: ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cus ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ con ┆ 30: ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ cen ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ser ┆     ┆     ┆     │

In [71]:
# ==========================================
# --- FINAL AGGREGATION (IEX + RTA) ---
# ==========================================

# ------------------------------------------
# 1. IEX AGGREGATION (Scheduled Data - In Heads)
# ------------------------------------------
leave_list = ['Unscheduled', 'PTO', 'Termination', 'Offline', 'Paid Leave']

lob_mapping_extended = {
    "GEN_GEN_EN_GCS_GLG_CHT": "Lodging chat",
    "GEN_GEN_EN_GCS_GNL_CHT": "Non-Lodging chat",
    "GEN_GEN_EN_GCS_GLG_CHT_Concentrix": "Lodging chat",
    "GEN_GEN_EN_GCS_GNL_CHT_Concentrix": "Non-Lodging chat",
    "Lodging": "Lodging chat",
    "Lodging_Nesting": "Lodging chat",
    "Non_Lodging": "Non-Lodging chat"
}

hc_subset = HC_EXTEND_COMBINED.select(["Date", "Email Id", "LOB"])

IEX_Aggregated = IEX_Intervals_Input.join(
    hc_subset, left_on=["Date_Converted", "Email Id"], right_on=["Date", "Email Id"], how="left"
).with_columns(
    pl.col("LOB").replace_strict(lob_mapping_extended, default=pl.col("LOB"))
).group_by(
    ["LOB", "VNT_Intervals", "PST_Intervals"]
).agg([
    (pl.col("Duration").filter(pl.col("Scheduled Activity").is_in(["Open Time", "Extra Hours"])).sum() * 2).alias("Scheduled_Open_Time"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Break")).sum() * 2).alias("Scheduled_Break"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Lunch")).sum() * 2).alias("Scheduled_Lunch"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").str.contains("Training|Coaching")).sum() * 2).alias("Scheduled_Training/Coaching"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity").is_in(leave_list)).sum() * 2).alias("Scheduled_Leave"),
    (pl.col("Duration").filter(pl.col("Scheduled Activity") == "No Call/No Show").sum() * 2).alias("Scheduled_NCNS")
])

# ------------------------------------------
# 2. RTA AGGREGATION (Actual Data - In Heads)
# ------------------------------------------
rta_lob_mapping = {
    "Chat_OD_EN_Lodging": "Lodging chat",
    "Chat_OD_EN_Car_Activity": "Lodging chat",
    "Chat_OD_Retail_Lodging_GLB_EN_Nesting": "Lodging chat",
    "Chat_OD_EN_Dual_GDS": "Non-Lodging chat",
    "Chat_OD_EN_Amadeus": "Non-Lodging chat"
}

tc_states = ["Training", "Coaching", "Team Meeting", "Restroom", "System Issue"]

RTA_AGGREGATION = Agent_Activity_Intervals_Input.filter(
).with_columns(
    pl.col("Agent Queue Group Name").replace_strict(rta_lob_mapping, default=None).alias("LOB")
).filter(
    pl.col("LOB").is_not_null()
).group_by(
    ["LOB", "VNT_Intervals"]
).agg([
    (pl.col("Duration").filter(
        pl.col("Agent State").str.contains("Break") & 
        (pl.col("Productive Aux Flag (Yes / No)") == "No")
    ).sum() * 2).alias("Actual_Break"),
    
    (pl.col("Duration").filter(
        pl.col("Agent State").str.contains("Lunch") & 
        (pl.col("Productive Aux Flag (Yes / No)") == "No")
    ).sum() * 2).alias("Actual_Lunch"),
    
    (pl.col("Duration").filter(
        pl.col("Agent State").is_in(tc_states) & 
        (pl.col("Productive Aux Flag (Yes / No)") == "No")
    ).sum() * 2).alias("Actual_Training_Coaching")
])

# ------------------------------------------
# 3. FINAL AGGREGATION (Merge IEX and RTA)
# ------------------------------------------
FINAL_AGGREGATION = IEX_Aggregated.join(
    RTA_AGGREGATION,
    on=["LOB", "VNT_Intervals"],
    how="left"
).fill_null(0)

FINAL_AGGREGATION

shape: (6_118, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ LOB    ┆ VNT_In ┆ PST_In ┆ Sched ┆ Sched ┆ Sched ┆ Sched ┆ Sched ┆ Sched ┆ Actua ┆ Actua ┆ Actua │
│ ---    ┆ terval ┆ terval ┆ uled_ ┆ uled_ ┆ uled_ ┆ uled_ ┆ uled_ ┆ uled_ ┆ l_Bre ┆ l_Lun ┆ l_Tra │
│ str    ┆ s      ┆ s      ┆ Open_ ┆ Break ┆ Lunch ┆ Train ┆ Leave ┆ NCNS  ┆ ak    ┆ ch    ┆ ining │
│        ┆ ---    ┆ ---    ┆ Time  ┆ ---   ┆ ---   ┆ ing/C ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ _Coac │
│        ┆ dateti ┆ dateti ┆ ---   ┆ f64   ┆ f64   ┆ oachi ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ hing  │
│        ┆ me[μs] ┆ me[μs] ┆ f64   ┆       ┆       ┆ ng    ┆       ┆       ┆       ┆       ┆ ---   │
│        ┆        ┆        ┆       ┆       ┆       ┆ ---   ┆       ┆       ┆       ┆       ┆ f64   │
│        ┆        ┆        ┆       ┆       ┆       ┆ f64   ┆       ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ Non-Lo ┆ 2026-0 ┆ 2026-0 ┆ 5.5   ┆ 0.0   ┆ 5.5   ┆ 0.0   ┆ 0.0   ┆ 1.0   ┆ 0.0   ┆ 4.239 ┆ 0.0   │
│ dging  ┆ 3-17   ┆ 3-16   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 444   ┆       │
│ chat   ┆ 12:00: ┆ 22:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 12.16 ┆ 0.0   ┆ 9.833 ┆ 0.0   ┆ 3.0   ┆ 2.0   ┆ 0.0   ┆ 9.52  ┆ 0.0   │
│ g chat ┆ 3-15   ┆ 3-14   ┆ 6667  ┆       ┆ 333   ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 02:00: ┆ 12:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 12.16 ┆ 1.833 ┆ 2.0   ┆ 0.0   ┆ 5.0   ┆ 3.0   ┆ 0.988 ┆ 0.622 ┆ 0.0   │
│ g chat ┆ 4-05   ┆ 4-04   ┆ 6667  ┆ 333   ┆       ┆       ┆       ┆       ┆ 333   ┆ 778   ┆       │
│        ┆ 13:00: ┆ 23:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 23.33 ┆ 1.666 ┆ 1.0   ┆ 0.0   ┆ 1.0   ┆ 0.0   ┆ 0.877 ┆ 2.898 ┆ 0.0   │
│ g chat ┆ 3-22   ┆ 3-21   ┆ 3333  ┆ 667   ┆       ┆       ┆       ┆       ┆ 222   ┆ 333   ┆       │
│        ┆ 03:30: ┆ 13:30: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 22.5  ┆ 0.0   ┆ 5.5   ┆ 0.0   ┆ 5.666 ┆ 1.0   ┆ 0.0   ┆ 6.554 ┆ 0.0   │
│ g chat ┆ 1-07   ┆ 1-06   ┆       ┆       ┆       ┆       ┆ 667   ┆       ┆       ┆ 444   ┆       │
│        ┆ 02:30: ┆ 11:30: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ …      ┆ …      ┆ …      ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 14.5  ┆ 0.5   ┆ 0.0   ┆ 0.0   ┆ 5.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ g chat ┆ 4-25   ┆ 4-24   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 07:00: ┆ 17:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Non-Lo ┆ 2026-0 ┆ 2026-0 ┆ 3.5   ┆ 0.5   ┆ 0.0   ┆ 0.0   ┆ 2.0   ┆ 0.0   ┆ 0.5   ┆ 0.0   ┆ 0.0   │
│ dging  ┆ 4-11   ┆ 4-11   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ chat   ┆ 22:00: ┆ 08:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 12.5  ┆ 0.0   ┆ 7.5   ┆ 0.0   ┆ 0.0   ┆ 10.0  ┆ 0.0   ┆ 4.507 ┆ 0.608 │
│ g chat ┆ 2-23   ┆ 2-22   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 778   ┆ 333   │
│        ┆ 02:00: ┆ 11:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 17.83 ┆ 1.166 ┆ 0.0   ┆ 0.0   ┆ 2.0   ┆ 6.0   ┆ 0.51  ┆ 0.0   ┆ 0.0   │
│ g chat ┆ 3-02   ┆ 3-01   ┆ 3333  ┆ 667   ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 14:30: ┆ 23:30: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Lodgin ┆ 2026-0 ┆ 2026-0 ┆ 6.333 ┆ 0.666 ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 1.543 ┆ 0.0   ┆ 0.0   │
│ g chat ┆ 4-18   ┆ 4-17   ┆ 333   ┆ 667   ┆       ┆       ┆       ┆       ┆ 889   ┆       ┆       │
│        ┆ 04:00: ┆ 14:00: ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ 00     ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [68]:
# --- IC HCM DETAILS ---
# Filter specifically for HCM and join with FINAL_AGGREGATION (Scheduled + Actual)
IC_HCM_Details_Log = Final_Merged_Data.filter(
    pl.col("Site") == "Concentrix (Ho Chi Minh City)"
).join(
    FINAL_AGGREGATION,
    on=["LOB", "VNT_Intervals", "PST_Intervals"],
    how="left"
).select([
    "LOB", "PST_Month", "PST_Date", "PST_Intervals", "PST_Interval_Range",
    "VNT_Date", "VNT_Intervals", "VNT_Interval_Range",
    
    "Forecast Productive Hour (Sum)", "Forecast Heads", 
    "Total_LOB_Productive_Hours", "Actual Heads",
    "Staffing Attainment (Pct)", "Interval Compliance (Pct)", "IC Status", "Occupancy", "Billable Hours (Sum)",
    
    "Site", "Req_Site_Level", "Site Req Heads", 
    "Site_Productive_Hours", "Site Actual Heads",
    "Staffing Attainment (Pct)_Site_Level", "Occupancy_Site_Level", "Handle Count (Sum)",
    
    "Scheduled_Open_Time", "Scheduled_Break", "Scheduled_Lunch", 
    "Scheduled_Training/Coaching", "Scheduled_Leave", "Scheduled_NCNS",
    
    "Actual_Break", "Actual_Lunch", "Actual_Training_Coaching"
])

In [69]:
# --- IC FORECASTING ---
forecast_unpl_pct = 0.10

# 1. Base query from OU Data
ou_forecast_base = OU_Data.filter(pl.col("Site") == "Concentrix (Ho Chi Minh City)").select([
    "LOB", "Site", "PST_Intervals", "VNT_Intervals", "Req"
]).rename({"Req": "Req_Site_Level"})

# 2. Join with IEX & Execute mathematical conversions
ic_forecast = ou_forecast_base.join(
    IEX_Aggregated, on=["LOB", "VNT_Intervals", "PST_Intervals"], how="left"
).with_columns([
    # Convert Hours to Heads (Multiply by 2)
    (pl.col("Req_Site_Level") * 2).alias("Site Req Heads"),
    (pl.col("Scheduled_Open_Time") * 2).alias("Scheduled_Open_Time"),
    (pl.col("Scheduled_Break") * 2).alias("Scheduled_Break"),
    (pl.col("Scheduled_Lunch") * 2).alias("Scheduled_Lunch"),
    (pl.col("Scheduled_Training/Coaching") * 2).alias("Scheduled_Training/Coaching"),
    (pl.col("Scheduled_Leave") * 2).alias("Scheduled_Leave"),
    (pl.col("Scheduled_NCNS") * 2).alias("Scheduled_NCNS"),
    
    # Base Coverage %
    pl.when(pl.col("Req_Site_Level") == 0).then(None).otherwise(
        (pl.col("Scheduled_Open_Time") * 2) / (pl.col("Req_Site_Level") * 2)
    ).alias("Forecast_Coverage_Pct"),
    
    # Date/Time Formatting
    pl.col("PST_Intervals").dt.strftime("%Y-%m").alias("PST_Month"),
    pl.col("PST_Intervals").dt.truncate("1w").dt.date().alias("PST_Week"),
    pl.col("PST_Intervals").dt.date().alias("PST_Date"),
    pl.concat_str([
        pl.col("PST_Intervals").dt.strftime("%H:%M"), pl.lit("-"),
        (pl.col("PST_Intervals") + pl.duration(minutes=30)).dt.strftime("%H:%M")
    ]).alias("PST_Interval_Range"),
    
    pl.col("VNT_Intervals").dt.date().alias("VNT_Date"),
    pl.concat_str([
        pl.col("VNT_Intervals").dt.strftime("%H:%M"), pl.lit("-"),
        (pl.col("VNT_Intervals") + pl.duration(minutes=30)).dt.strftime("%H:%M")
    ]).alias("VNT_Interval_Range")
]).with_columns([
    # Summing unproductive categories
    (
        pl.col("Scheduled_Break").fill_null(0) + pl.col("Scheduled_Lunch").fill_null(0) +
        pl.col("Scheduled_Training/Coaching").fill_null(0) + pl.col("Scheduled_Leave").fill_null(0) +
        pl.col("Scheduled_NCNS").fill_null(0)
    ).alias("Scheduled_Unproductive"),
    
    # Shrinkage mapping & HC loss calculation (Round up to nearest 0.5)
    pl.lit(forecast_unpl_pct).alias("Forecast_Unpl_Pct"),
    (((pl.col("Scheduled_Open_Time").fill_null(0) * forecast_unpl_pct) * 2).ceil() / 2).alias("Forecast_Lost_HC")
]).with_columns([
    # Adjusted coverages using HC loss
    pl.when(pl.col("Site Req Heads").fill_null(0) == 0).then(None).otherwise(
        (pl.col("Scheduled_Open_Time").fill_null(0) - pl.col("Forecast_Lost_HC")) / pl.col("Site Req Heads")
    ).alias("Forecast_2_Coverage_Pct"),
    
    (((pl.col("Scheduled_Open_Time").fill_null(0) - pl.col("Forecast_Lost_HC") - pl.col("Site Req Heads").fill_null(0)) * 2).ceil() / 2).alias("Forecast_HC_Surplus_Shortage")
]).select([
    "LOB", "PST_Month", "PST_Week", "PST_Date", "PST_Intervals", "PST_Interval_Range",
    "VNT_Date", "VNT_Intervals", "VNT_Interval_Range", "Site", "Req_Site_Level", "Site Req Heads",
    "Scheduled_Open_Time", "Scheduled_Break", "Scheduled_Lunch", "Scheduled_Training/Coaching",
    "Scheduled_Leave", "Scheduled_NCNS", "Scheduled_Unproductive", "Forecast_Coverage_Pct",
    "Forecast_Unpl_Pct", "Forecast_Lost_HC", "Forecast_HC_Surplus_Shortage", "Forecast_2_Coverage_Pct"
])

ic_forecast

shape: (10_752, 24)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ LOB ┆ PST ┆ PST ┆ PST ┆ PST ┆ PST ┆ VNT ┆ VNT ┆ VNT ┆ Sit ┆ Req ┆ Sit ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ Sch ┆ For ┆ For ┆ For ┆ For ┆ For │
│ --- ┆ _Mo ┆ _We ┆ _Da ┆ _In ┆ _In ┆ _Da ┆ _In ┆ _In ┆ e   ┆ _Si ┆ e   ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ eca ┆ eca ┆ eca ┆ eca ┆ eca │
│ str ┆ nth ┆ ek  ┆ te  ┆ ter ┆ ter ┆ te  ┆ ter ┆ ter ┆ --- ┆ te_ ┆ Req ┆ led ┆ led ┆ led ┆ led ┆ led ┆ led ┆ led ┆ st_ ┆ st_ ┆ st_ ┆ st_ ┆ st_ │
│     ┆ --- ┆ --- ┆ --- ┆ val ┆ val ┆ --- ┆ val ┆ val ┆ str ┆ Lev ┆ Hea ┆ _Op ┆ _Br ┆ _Lu ┆ _Tr ┆ _Le ┆ _NC ┆ _Un ┆ Cov ┆ Unp ┆ Los ┆ HC_ ┆ 2_C │
│     ┆ str ┆ dat ┆ dat ┆ s   ┆ _Ra ┆ dat ┆ s   ┆ _Ra ┆     ┆ el  ┆ ds  ┆ en_ ┆ eak ┆ nch ┆ ain ┆ ave ┆ NS  ┆ pro ┆ era ┆ l_P ┆ t_H ┆ Sur ┆ ove │
│     ┆     ┆ e   ┆ e   ┆ --- ┆ nge ┆ e   ┆ --- ┆ nge ┆     ┆ --- ┆ --- ┆ Tim ┆ --- ┆ --- ┆ ing ┆ --- ┆ --- ┆ duc ┆ ge_ ┆ ct  ┆ C   ┆ plu ┆ rag │
│     ┆     ┆     ┆     ┆ dat ┆ --- ┆     ┆ dat ┆ --- ┆     ┆ f64 ┆ f64 ┆ e   ┆ f64 ┆ f64 ┆ /Co ┆ f64 ┆ f64 ┆ tiv ┆ Pct ┆ --- ┆ --- ┆ s_S ┆ e_P │
│     ┆     ┆     ┆     ┆ eti ┆ str ┆     ┆ eti ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ ach ┆     ┆     ┆ e   ┆ --- ┆ f64 ┆ f64 ┆ hor ┆ ct  │
│     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ ing ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆ tag ┆ --- │
│     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆ e   ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Lod ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 00: ┆ 202 ┆ 202 ┆ 15: ┆ Con ┆ 2.4 ┆ 4.9 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ 0.1 ┆ 0.0 ┆ -4. ┆ 0.0 │
│ gin ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 00- ┆ 5-1 ┆ 5-1 ┆ 00- ┆ cen ┆ 55  ┆ 1   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆ 5   ┆     │
│ g   ┆ 2   ┆ 2-2 ┆ 2-2 ┆ 2-2 ┆ 00: ┆ 2-2 ┆ 2-2 ┆ 15: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 30  ┆ 9   ┆ 9   ┆ 30  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 15: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 00: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 00: ┆ 202 ┆ 202 ┆ 15: ┆ Con ┆ 2.4 ┆ 4.8 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ 0.1 ┆ 0.0 ┆ -4. ┆ 0.0 │
│ gin ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 30- ┆ 5-1 ┆ 5-1 ┆ 30- ┆ cen ┆ 25  ┆ 5   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆ 5   ┆     │
│ g   ┆ 2   ┆ 2-2 ┆ 2-2 ┆ 2-2 ┆ 01: ┆ 2-2 ┆ 2-2 ┆ 16: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 00  ┆ 9   ┆ 9   ┆ 00  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 15: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆ 30: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 01: ┆ 202 ┆ 202 ┆ 16: ┆ Con ┆ 2.0 ┆ 4.1 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ 0.1 ┆ 0.0 ┆ -4. ┆ 0.0 │
│ gin ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 00- ┆ 5-1 ┆ 5-1 ┆ 00- ┆ cen ┆ 5   ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆ 0   ┆     │
│ g   ┆ 2   ┆ 2-2 ┆ 2-2 ┆ 2-2 ┆ 01: ┆ 2-2 ┆ 2-2 ┆ 16: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 30  ┆ 9   ┆ 9   ┆ 30  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆ 16: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 00: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 01: ┆ 202 ┆ 202 ┆ 16: ┆ Con ┆ 2.2 ┆ 4.5 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ 0.1 ┆ 0.0 ┆ -4. ┆ 0.0 │
│ gin ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 30- ┆ 5-1 ┆ 5-1 ┆ 30- ┆ cen ┆ 55  ┆ 1   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆ 5   ┆     │
│ g   ┆ 2   ┆ 2-2 ┆ 2-2 ┆ 2-2 ┆ 02: ┆ 2-2 ┆ 2-2 ┆ 17: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 00  ┆ 9   ┆ 9   ┆ 00  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆ 16: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆ 30: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 02: ┆ 202 ┆ 202 ┆ 17: ┆ Con ┆ 1.9 ┆ 3.8 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ 0.1 ┆ 0.0 ┆ -3. ┆ 0.0 │
│ gin ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆ 00- ┆ 5-1 ┆ 5-1 ┆ 00- ┆ cen ┆ 25  ┆ 5   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆     ┆     ┆ 5   ┆     │
│ g   ┆ 2   ┆ 2-2 ┆ 2-2 ┆ 2-2 ┆ 02: ┆ 2-2 ┆ 2-2 ┆ 17: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 30  ┆ 9   ┆ 9   ┆ 30  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 02: ┆     ┆     ┆ 17: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 00: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ Non ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 21: ┆ 202 ┆ 202 ┆ 11: ┆ Con ┆ 1.8 ┆ 3.7 ┆ 10. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 2.0 ┆ 2.6 ┆ 0.1 ┆ 1.0 ┆ 5.5 ┆ 2.4 │
│ -Lo ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 6-0 ┆ 6-0 ┆ 30- ┆ cen ┆ 55  ┆ 1   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 954 ┆     ┆     ┆     ┆ 258 │
│ dgi ┆ 4   ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 22: ┆ 4-2 ┆ 4-2 ┆ 12: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18  ┆     ┆     ┆     ┆ 76  │
│ ng  ┆     ┆ 3   ┆ 9   ┆ 9   ┆ 00  ┆ 0   ┆ 0   ┆ 00  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆     ┆     ┆ 21: ┆     ┆     ┆ 11: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆ 30: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Non ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 22: ┆ 202 ┆ 202 ┆ 12: ┆ Con ┆ 1.3 ┆ 2.7 ┆ 4.0 ┆ 2.0 ┆ 4.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 8.0 ┆ 1.4 ┆ 0.1 ┆ 0.5 ┆ 1.0 ┆ 1.2 │
│ -Lo ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 6-0 ┆ 6-0 ┆ 00- ┆ cen ┆ 8   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 492 ┆     ┆     ┆     ┆ 681 │
│ dgi ┆ 4   ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 22: ┆ 4-2 ┆ 4-2 ┆ 12: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 75  ┆     ┆     ┆     ┆ 16  │
│ ng  ┆     ┆ 3   ┆ 9   ┆ 9   ┆ 30  ┆ 0   ┆ 0   ┆ 30  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆     ┆     ┆ 22: ┆     ┆     ┆ 12: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 00: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Non ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 22: ┆ 202 ┆ 202 ┆ 12: ┆ Con ┆ 1.8 ┆ 3.6 ┆ 6.0 ┆ 0.0 ┆ 4.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 6.0 ┆ 1.6 ┆ 0.1 ┆ 1.0 ┆ 1.5 ┆ 1.3 │
│ -Lo ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 6-0 ┆ 6-0 ┆ 30- ┆ cen ┆ 45  ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 260 ┆     ┆     ┆     ┆ 550 │
│ dgi ┆ 4   ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 23: ┆ 4-2 ┆ 4-2 ┆ 13: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16  ┆     ┆     ┆     ┆ 14  │
│ ng  ┆     ┆ 3   ┆ 9   ┆ 9   ┆ 00  ┆ 0   ┆ 0   ┆ 00  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆     ┆     ┆ 22: ┆     ┆     ┆ 12: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆ 30: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Non ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 23: ┆ 202 ┆ 202 ┆ 13: ┆ Con ┆ 3.2 ┆ 6.5 ┆ 10. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 2.0 ┆ 1.5 ┆ 0.1 ┆ 1.0 ┆ 2.5 ┆ 1.3 │
│ -Lo ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 00- ┆ 6-0 ┆ 6-0 ┆ 00- ┆ cen ┆ 7   ┆ 4   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 290 ┆     ┆     ┆     ┆ 761 │
│ dgi ┆ 4   ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 23: ┆ 4-2 ┆ 4-2 ┆ 13: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 52  ┆     ┆     ┆     ┆ 47  │
│ ng  ┆     ┆ 3   ┆ 9   ┆ 9   ┆ 30  ┆ 0   ┆ 0   ┆ 30  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆     ┆     ┆ 23: ┆     ┆     ┆ 13: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ 00: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Non ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 23: ┆ 202 ┆ 202 ┆ 13: ┆ Con ┆ 3.5 ┆ 7.1 ┆ 10. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 2.0 ┆ 1.4 ┆ 0.1 ┆ 1.0 ┆ 2.0 ┆ 1.2 │
│ -Lo ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 30- ┆ 6-0 ┆ 6-0 ┆ 30- ┆ cen ┆ 6   ┆ 2   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 044 ┆     ┆     ┆     ┆ 640 │
│ dgi ┆ 4   ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 00: ┆ 4-2 ┆ 4-2 ┆ 14: ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 94  ┆     ┆     ┆     ┆ 45  │
│ ng  ┆     ┆ 3   ┆ 9   ┆ 9   ┆ 00  ┆ 0   ┆ 0   ┆ 00  ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆     ┆     ┆     ┆ 23: ┆     ┆     ┆ 13: ┆     ┆ (Ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆ 30: ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ 00  ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [70]:
# --- DATA EXPORT ---
dt_format = "%Y-%m-%d %H:%M:%S"

# Dictionary holding filename and its corresponding dataframe
exports = {
    "Agent_Avoidance_RawData.csv": Agent_Avoidance_RawData,
    "Schedule_Adherence_Gap.csv": Schedule_Adherence_Gap,
    "Agent_Rest_Compliance_Log.csv": Agent_Rest_Compliance_Log,
    "IC_Details_Log.csv": Final_Merged_Data,
    "IC_HCM_Details_Log.csv": IC_HCM_Details_Log,
    "IC_Forecast.csv": ic_forecast
}

# Loop through and write each CSV cleanly
for filename, df in exports.items():
    df.write_csv(
        os.path.join(output_folder, filename),
        datetime_format=dt_format,
        include_bom=True
    )
    
print(f"Successfully exported {len(exports)} files to {output_folder}")

Successfully exported 6 files to C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_NON_COMPLIANCE