In [21]:
import polars as pl
from datetime import datetime
from datetime import date, time
import glob
import os

In [22]:
first_glob = os.path.expanduser("~").replace("\\", "/")

exclibur_path = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Performance Latest Version.xlsb'
output_req = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Req.csv'

df = pl.read_excel(
    exclibur_path,
    sheet_name="Requierd Hours",
    engine="calamine",
    has_header=False,
    columns=list(range(46))
)
new_headers = [str(val).split(" ")[0] for val in df.row(0)]
rename_mapping = dict(zip(df.columns, new_headers))
result_df = df.slice(1, 980).rename(rename_mapping)
result_df = result_df.with_columns([
    pl.col("PSP").replace_strict({"Chat Non-Lodging": "Non-Lodging chat"}, default=pl.col("PSP")),
    pl.col("Interval").str.to_datetime("%Y-%m-%d %H:%M:%S", strict=False).dt.strftime("%H:%M:%S"),
    pl.exclude("PSP", "Site", "Interval").cast(pl.Float64, strict=False)
])
result_df = result_df.filter(
    pl.col("PSP").is_in(["Lodging chat", "Non-Lodging chat"])
).sort("PSP", maintain_order=True)
result_df.write_csv(output_req, include_bom=True)
print(result_df['PSP'].unique(maintain_order=True))
result_df.head(10)

shape: (2,)
Series: 'PSP' [str]
[
	"Lodging chat"
	"Non-Lodging chat"
]

shape: (10, 46)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ PSP ┆ Sit ┆ Int ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 202 ┆ MTD │
│ --- ┆ e   ┆ erv ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ --- │
│ str ┆ --- ┆ al  ┆ 3-3 ┆ 3-3 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-0 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-2 ┆ 4-3 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-0 ┆ 5-1 ┆ f64 │
│     ┆ str ┆ --- ┆ 0   ┆ 1   ┆ 1   ┆ 2   ┆ 3   ┆ 4   ┆ 5   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 0   ┆ 1   ┆ 2   ┆ 3   ┆ 4   ┆ 5   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 0   ┆ 1   ┆ 2   ┆ 3   ┆ 4   ┆ 5   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 0   ┆ 1   ┆ 2   ┆ 3   ┆ 4   ┆ 5   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 0   ┆     │
│     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Lod ┆ Con ┆ 00: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 │
│ gin ┆ cen ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 00: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0.0 │
│ gin ┆ cen ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 01: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.4 ┆ 1.4 ┆ 1.4 ┆ 1.2 ┆ 1.4 ┆ 1.4 ┆ 2.1 ┆ 3.5 ┆ 3.0 ┆ 3.0 ┆ 4.0 ┆ 3.5 ┆ 2.0 ┆ 2.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 31. │
│ gin ┆ cen ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 7   ┆ 1   ┆     ┆ 2   ┆ 55  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 49  │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 01: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.6 ┆ 1.5 ┆ 1.6 ┆ 1.1 ┆ 1.5 ┆ 1.5 ┆ 2.1 ┆ 3.5 ┆ 3.0 ┆ 2.5 ┆ 3.5 ┆ 3.5 ┆ 2.0 ┆ 1.5 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 30. │
│ gin ┆ cen ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 9   ┆ 45  ┆ 05  ┆ 25  ┆ 8   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 685 │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 02: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.9 ┆ 4.3 ┆ 3.1 ┆ 2.4 ┆ 3.2 ┆ 4.0 ┆ 1.3 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 4.0 ┆ 2.5 ┆ 1.5 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 41. │
│ gin ┆ cen ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 95  ┆ 55  ┆ 3   ┆ 2   ┆ 45  ┆ 75  ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 55  │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 02: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.4 ┆ 3.8 ┆ 3.9 ┆ 2.4 ┆ 2.5 ┆ 3.9 ┆ 2.1 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 3.0 ┆ 2.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 42. │
│ gin ┆ cen ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 85  ┆ 8   ┆ 5   ┆ 2   ┆ 9   ┆ 95  ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 95  │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 03: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 3.1 ┆ 2.2 ┆ 1.8 ┆ 5.2 ┆ 4.6 ┆ 2.0 ┆ 3.5 ┆ 3.0 ┆ 3.0 ┆ 4.0 ┆ 4.0 ┆ 3.0 ┆ 2.5 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 45. │
│ gin ┆ cen ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 7   ┆ 6   ┆ 3   ┆ 5   ┆ 5   ┆ 95  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 275 │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 03: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 4.5 ┆ 6.4 ┆ 5.0 ┆ 3.1 ┆ 4.0 ┆ 4.5 ┆ 6.4 ┆ 3.5 ┆ 3.5 ┆ 3.5 ┆ 4.0 ┆ 4.5 ┆ 3.0 ┆ 2.5 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 58. │
│ gin ┆ cen ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55  ┆ 25  ┆ 95  ┆ 4   ┆ 75  ┆ 7   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 84  │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 04: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.9 ┆ 3.5 ┆ 2.5 ┆ 3.7 ┆ 3.7 ┆ 2.3 ┆ 1.3 ┆ 2.0 ┆ 3.0 ┆ 2.5 ┆ 2.5 ┆ 2.5 ┆ 1.5 ┆ 3.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 35. │
│ gin ┆ cen ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 15  ┆ 75  ┆ 4   ┆ 3   ┆ 8   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 18  │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Lod ┆ Con ┆ 04: ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.6 ┆ 5.6 ┆ 5.6 ┆ 6.0 ┆ 5.0 ┆ 3.0 ┆ 2.6 ┆ 3.0 ┆ 3.0 ┆ 4.0 ┆ 4.0 ┆ 3.0 ┆ 3.5 ┆ 4.0 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 55. │
│ gin ┆ cen ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25  ┆ 2   ┆ 85  ┆ 9   ┆ 6   ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 185 │
│ g   ┆ tri ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cha ┆ x   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆ (Pu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ne) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [23]:
def process_psp_hours(file_path):
    try:
        df_raw = pl.read_excel(source=file_path, has_header=False, infer_schema_length=0)
        
        header_vals = df_raw.row(0)
        new_columns = [
            val.strftime("%Y-%m-%d") if isinstance(val, datetime) else str(val).strip() if val is not None else "Unknown" 
            for val in header_vals
        ]
        df_raw.columns = new_columns
        
        df = df_raw.slice(1).with_columns(
            pl.col("Interval").cast(pl.String).str.replace(r"^.*1899-12-31\s+", "").str.slice(0, 8).alias("Interval")
        )
        
        final_df = (df.unpivot(index=["LOB", "Site", "Interval"], variable_name="Date_Str", value_name="Value")
            .with_columns([
                (pl.col("Date_Str").str.slice(0, 10) + " " + pl.col("Interval"))
                .str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S", strict=False)
                .dt.truncate("1m").alias("PST_Datetime"),
                
                pl.col("Value").cast(pl.Float64, strict=False).fill_null(0.0).alias("PSP"),
                pl.col("LOB").str.strip_chars(), 
                pl.col("Site").str.strip_chars()
            ])
            .with_columns(
                pl.col("PSP").sum().over(["LOB", "PST_Datetime"]).alias("Total PSP")
            )
        )
        return final_df.select(["LOB", "Site", "PST_Datetime", "PSP", "Total PSP"])
    except Exception:
        return pl.DataFrame()

def process_productive_hours(folder_path):
    file_pattern = os.path.join(folder_path, "*.csv")
    all_files = sorted(glob.glob(file_pattern))
    
    dfs = []
    
    for file in all_files:
        df_temp = pl.read_csv(
            file,
            infer_schema_length=0,
            ignore_errors=True,
            encoding="utf-8",
        )
        
        rename_map = {
            "Forecast Group Name": "LOB",
            "Business Location": "Site",
            "Interval": "Raw_Interval",
            "Productive Hours (Sum)": "Productive Hours"
        }
        existing_rename = {k: v for k, v in rename_map.items() if k in df_temp.columns}
        if existing_rename:
            df_temp = df_temp.rename(existing_rename)
        
        if "Productive Hours" in df_temp.columns:
            df_temp = df_temp.with_columns(
                pl.col("Productive Hours")
                .cast(pl.String)
                .str.strip_chars()
                .str.replace_all(r",", "")
                .str.replace_all(r"[^\d.-]", "")
                .replace({"": "0", "-": "0", "N/A": "0", "null": "0"})
                .cast(pl.Float64, strict=False)
                .fill_null(0.0)
                .alias("Productive Hours")
            )
        
        for col in ["LOB", "Site", "Raw_Interval"]:
            if col in df_temp.columns:
                df_temp = df_temp.with_columns(pl.col(col).cast(pl.String).str.strip_chars())
        
        dfs.append(df_temp)
    
    df_raw = pl.concat(dfs, how="vertical_relaxed")
    
    df = df_raw.select([
        pl.col("LOB"),
        pl.col("Site"),
        pl.col("Raw_Interval"),
        pl.col("Productive Hours")
    ])
    
    df = df.with_columns([
        pl.when(pl.col("LOB") == "GEN_GEN_EN_GCS_GLG_CHT")
        .then(pl.lit("Lodging chat"))
        .when(pl.col("LOB") == "GEN_GEN_EN_GCS_GNL_CHT")
        .then(pl.lit("Non-Lodging chat"))
        .otherwise(pl.col("LOB"))
        .str.strip_chars()
        .alias("LOB"),
        pl.col("Site").str.strip_chars().alias("Site")
    ])

    df_agg = df.group_by(["LOB", "Site", "Raw_Interval"]).agg(
        pl.col("Productive Hours").sum()
    )

    df_processed = df_agg.with_columns(
        pl.col("Raw_Interval")
          .str.strip_chars()
          .str.to_datetime(format="%m/%d/%Y %H:%M", strict=False)
          .fill_null(
              pl.col("Raw_Interval")
                .str.to_datetime(format="%Y-%m-%d %H:%M:%S", strict=False)
          )
          .dt.truncate("1m")
          .alias("PST_Datetime")
    ).filter(
        pl.col("PST_Datetime").is_not_null()
    ).with_columns(
        pl.col("Productive Hours")
          .sum()
          .over(["LOB", "PST_Datetime"])
          .alias("Total Productive Hours")
    )

    return df_processed.select([
        "LOB", "Site", "PST_Datetime", "Productive Hours", "Total Productive Hours"
    ])

def process_vendor_msp(folder_path: str) -> pl.DataFrame:
    files = glob.glob(os.path.join(folder_path, "*.csv"))
    
    if not files:
        return pl.DataFrame()

    target_columns = [
        "Vendor Forecast Group Name",
        "Interval Time",
        "Forecast Productive Hour (Sum)",
        "Occupancy",
        "Staffing Attainment (Pct)",
        "Interval Compliance (Pct)"
    ]
    
    schema_overrides = {
        "Forecast Productive Hour (Sum)": pl.Float64,
        "Occupancy": pl.Float64,
        "Staffing Attainment (Pct)": pl.Float64,
        "Interval Compliance (Pct)": pl.Float64,
        "Interval Time": pl.String
    }

    dfs = []
    
    for f in files:
        try:
            d = pl.read_csv(
                f,
                columns=target_columns,
                schema_overrides=schema_overrides,
                infer_schema_length=0
            )
            dfs.append(d)
        except Exception:
            continue

    if not dfs:
        return pl.DataFrame()

    df = pl.concat(dfs, how="vertical")

    df_processed = df.with_columns([
        pl.when(pl.col("Vendor Forecast Group Name") == "GEN_GEN_EN_GCS_GLG_CHT_Concentrix")
          .then(pl.lit("Lodging chat"))
          .when(pl.col("Vendor Forecast Group Name") == "GEN_GEN_EN_GCS_GNL_CHT_Concentrix")
          .then(pl.lit("Non-Lodging chat"))
          .otherwise(pl.col("Vendor Forecast Group Name"))
          .alias("LOB"),

        pl.coalesce([
            pl.col("Interval Time").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S", strict=False),
            pl.col("Interval Time").str.strptime(pl.Datetime, format="%m/%d/%Y %H:%M", strict=False),
            pl.col("Interval Time").str.strptime(pl.Datetime, format="%m/%d/%Y %I:%M:%S %p", strict=False)
        ]).alias("PST_Datetime"),

        pl.col("Forecast Productive Hour (Sum)").alias("MSP"),
        pl.col("Occupancy"),
        pl.col("Staffing Attainment (Pct)"),
        pl.col("Interval Compliance (Pct)")
    ])

    return df_processed.select([
        "LOB", 
        "PST_Datetime", 
        "MSP", 
        "Occupancy", 
        "Staffing Attainment (Pct)", 
        "Interval Compliance (Pct)"
    ])

def calculate_msp_distribution(df):
    df = df.with_columns([
        pl.col("Productive Hours").cast(pl.Float64).fill_null(0.0),
        pl.col("Total Productive Hours").cast(pl.Float64).fill_null(0.0),
        pl.col("MSP").cast(pl.Float64).fill_null(0.0).round(4),
        pl.col("PSP").cast(pl.Float64).fill_null(0.0).round(4),
        pl.col("Total PSP").cast(pl.Float64).fill_null(0.0).round(4),
        
        (pl.col("PST_Datetime").dt.strftime("%H:%M") + "-" +
         (pl.col("PST_Datetime") + pl.duration(minutes=29)).dt.strftime("%H:%M")).alias("PST_Interval_Range"),
        
        pl.col("PST_Datetime").dt.time().alias("PST_Interval"),
        pl.col("PST_Datetime").dt.date().alias("Date"),
        
        (pl.col("PST_Datetime")
         .dt.replace_time_zone("America/Los_Angeles", ambiguous="earliest", non_existent="null")
         .dt.convert_time_zone("Asia/Ho_Chi_Minh")
         .dt.replace_time_zone(None)
         .alias("VNT_Datetime")
        )
    ])
    
    df = df.with_columns([
        (pl.col("MSP") - pl.col("Total PSP")).round(4).alias("Variance (MSP-PSP)"),
        
        pl.when(pl.col("Site").str.contains("Ho Chi Minh"))
          .then(pl.col("PSP"))
          .otherwise(0.0)
          .sum().over(["LOB", "PST_Datetime"])
          .round(4).alias("PSP_HCM")
    ]).with_columns(
        (pl.col("Total PSP") - pl.col("PSP_HCM")).round(4).alias("Total_PSP_Non_HCM")
    )

    is_lodging = pl.col("LOB").str.to_lowercase().str.contains("lodging chat")
    is_hcm = pl.col("Site").str.contains("Ho Chi Minh")
    is_single_site = (pl.col("PSP") - pl.col("Total PSP")).abs() < 0.0001
    is_positive_var = pl.col("Variance (MSP-PSP)") > 0

    calc_prorated = pl.col("Variance (MSP-PSP)") * (pl.col("PSP") / pl.col("Total PSP"))
    calc_loss_sharing = pl.col("Variance (MSP-PSP)") * (pl.col("PSP") / pl.col("Total_PSP_Non_HCM").replace(0, 1))

    df = df.with_columns(
        pl.when(
            is_lodging & (is_positive_var | is_single_site)
        )
        .then(calc_prorated) 
        .otherwise(
            pl.when(is_lodging & is_hcm)
            .then(0.0)
            .otherwise(
                pl.when(is_lodging)
                .then(calc_loss_sharing)
                .otherwise(calc_prorated)
            )
        )
        .fill_nan(0.0).fill_null(0.0).round(4)
        .alias("Initial MSP allocation")
    )

    df = df.with_columns(
        pl.when((pl.col("PSP") + pl.col("Initial MSP allocation")) < -0.0001)
        .then(-pl.col("PSP"))
        .otherwise(pl.col("Initial MSP allocation"))
        .alias("Initial Adjustment")
    ).with_columns(
        (pl.col("Initial MSP allocation") - pl.col("Initial Adjustment")).alias("Pending MSP to be assigned")
    ).with_columns(
        pl.col("Pending MSP to be assigned").sum().over(["LOB", "PST_Datetime"]).alias("Total_Pending_Global")
    ).with_columns(
        pl.when(is_lodging & pl.col("Site").str.contains("Ho Chi Minh"))
        .then(pl.col("Initial Adjustment") + pl.col("Total_Pending_Global"))
        .otherwise(pl.col("Initial Adjustment"))
        .alias("Final adjustment")
    )

    return df.with_columns(
        (pl.col("PSP") + pl.col("Final adjustment")).alias("MSP site wise")
    )

def calculate_billable_logic(df):
    return (df
        .with_columns([
            pl.min_horizontal(["MSP site wise", "Productive Hours"]).alias("Billable"),
            pl.when(pl.col("Productive Hours") >= pl.col("MSP site wise"))
            .then(0.0).otherwise(pl.col("MSP site wise") - pl.col("Productive Hours")).alias("Billable Loss"),
            pl.when((pl.col("Productive Hours") - pl.col("MSP site wise")) < 0)
            .then(0.0).otherwise(pl.col("Productive Hours") - pl.col("MSP site wise")).alias("Over Production")
        ])
        .with_columns([
            pl.col("Billable Loss").sum().over(["LOB", "PST_Datetime"]).alias("Global Billable Loss"),
            pl.col("Over Production").sum().over(["LOB", "PST_Datetime"]).alias("Global Over Production")
        ])
        .with_columns(
            pl.when(pl.col("Billable Loss") > 0).then(0.0)
            .otherwise((pl.col("Global Billable Loss") * pl.col("Over Production")) / pl.col("Global Over Production"))
            .fill_nan(0.0).fill_null(0.0).alias("Compensated by other site")
        )
        .with_columns([
            pl.min_horizontal(["Over Production", "Compensated by other site"]).alias("Actual Compensation"),
            (pl.col("Billable") + pl.min_horizontal(["Over Production", "Compensated by other site"])).alias("Final Billable")
        ])
        .with_columns((pl.col("Final Billable") - pl.col("MSP site wise")).alias("Unbillable Hours"))
    )

if __name__ == "__main__":
    req_path = os.path.join(first_glob, r"Concentrix Corporation\WFM-Expedia-HCM - Branding files\Rawdata\OU.xlsx")
    prod_path = os.path.join(first_glob,r"Concentrix Corporation\WFM-Expedia-HCM - Branding files\Rawdata\INPUT_PRODUCTIVE_REVENUE")
    wfm_path = os.path.join(first_glob,r"Concentrix Corporation\WFM-Expedia-HCM - Branding files\Rawdata\INPUT_WORKFORCE_VENDOR")

    df_req = process_psp_hours(req_path)
    df_prod = process_productive_hours(prod_path)
    df_msp = process_vendor_msp(wfm_path)

    if not (df_req.is_empty() or df_prod.is_empty() or df_msp.is_empty()):
        df_merged = (
            df_req
            .join(df_prod, on=["LOB", "Site", "PST_Datetime"], how="left", coalesce=True)
            .join(df_msp, on=["LOB", "PST_Datetime"], how="left", coalesce=True)
        )
        
        df_distributed = calculate_msp_distribution(df_merged)
        df_final = calculate_billable_logic(df_distributed)
        
        final_cols = [
            "LOB", "Site", "Date", "PST_Interval", "PST_Interval_Range", "VNT_Interval", "VNT_Interval_Range", "PST_Datetime", "VNT_Datetime", 
            "PSP", "Total PSP", "MSP", "Variance (MSP-PSP)", "PSP_HCM", "Total_PSP_Non_HCM", 
            "Initial MSP allocation", "Initial Adjustment", "Pending MSP to be assigned", "Final adjustment", 
            "MSP site wise", "Productive Hours", "Total Productive Hours", "Billable", "Billable Loss", "Over Production", 
            "Compensated by other site", "Actual Compensation", "Final Billable", "Unbillable Hours",
            "Occupancy", "Staffing Attainment (Pct)", "Interval Compliance (Pct)"
        ]
        
        existing_cols = [c for c in final_cols if c in df_final.columns]
        df_result = df_final.select(existing_cols).sort(["LOB", "Site", "PST_Datetime"])
        output_file = "excalibur_raw.xlsx" 
        df_result.write_excel(output_file)
        
        print(f"Output saved to: {os.path.abspath(output_file)}")
    else:
        print("Một hoặc nhiều dataframe rỗng, không thể merge và xử lý.")

Output saved to: c:\Users\huuchinh.nguyen\Concentrix Corporation\WFM-Expedia-HCM - Branding files\BI_Task\CODE\Python_Code\excalibur_raw.xlsx

In [24]:
# 1. Config hiển thị full
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(200) # Tăng độ rộng để các cột số không bị xuống dòng

# 2. Định nghĩa danh sách cột cần lấy
target_cols = [
    "PST_Interval", "PSP", "Total PSP", "MSP", 
    "Variance (MSP-PSP)", "PSP_HCM", "Total_PSP_Non_HCM",
    "Initial MSP allocation", 
    "Initial Adjustment", 
    "Pending MSP to be assigned", 
    "Final adjustment", 
    "MSP site wise"
]

# 3. Thực hiện Lọc dòng (Filter) & Chọn cột (Select)
df_result.filter(
    (pl.col("Date") == date(2025, 12, 29)) & 
    (pl.col("PST_Interval") >= time(13, 0, 0)) &
    (pl.col("Site") == "Concentrix (Ho Chi Minh City)")
).select(target_cols).sort("PST_Interval")

shape: (44, 12)
┌──────────────┬───────┬───────────┬─────────┬────────────────────┬─────────┬───────────────────┬─────────────┬────────────────────┬────────────────────────────┬──────────────────┬───────────────┐
│ PST_Interval ┆ PSP   ┆ Total PSP ┆ MSP     ┆ Variance (MSP-PSP) ┆ PSP_HCM ┆ Total_PSP_Non_HCM ┆ Initial MSP ┆ Initial Adjustment ┆ Pending MSP to be assigned ┆ Final adjustment ┆ MSP site wise │
│ ---          ┆ ---   ┆ ---       ┆ ---     ┆ ---                ┆ ---     ┆ ---               ┆ allocation  ┆ ---                ┆ ---                        ┆ ---              ┆ ---           │
│ time         ┆ f64   ┆ f64       ┆ f64     ┆ f64                ┆ f64     ┆ f64               ┆ ---         ┆ f64                ┆ f64                        ┆ f64              ┆ f64           │
│              ┆       ┆           ┆         ┆                    ┆         ┆                   ┆ f64         ┆                    ┆                            ┆                  ┆               │
╞══════════════╪═══════╪═══════════╪═════════╪════════════════════╪═════════╪═══════════════════╪═════════════╪════════════════════╪════════════════════════════╪══════════════════╪═══════════════╡
│ 13:00:00     ┆ 3.265 ┆ 10.05     ┆ 12.1155 ┆ 2.0655             ┆ 3.265   ┆ 6.785             ┆ 0.671       ┆ 0.671              ┆ 0.0                        ┆ 0.671            ┆ 3.936         │
│ 13:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 13:30:00     ┆ 7.155 ┆ 10.05     ┆ 10.0955 ┆ 0.0455             ┆ 7.155   ┆ 2.895             ┆ 0.0324      ┆ 0.0324             ┆ 0.0                        ┆ 0.0324           ┆ 7.1874        │
│ 13:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 14:00:00     ┆ 4.92  ┆ 9.08      ┆ 10.8447 ┆ 1.7647             ┆ 4.92    ┆ 4.16              ┆ 0.9562      ┆ 0.9562             ┆ 0.0                        ┆ 0.9562           ┆ 5.8762        │
│ 14:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 14:30:00     ┆ 5.82  ┆ 9.4       ┆ 9.4216  ┆ 0.0216             ┆ 5.82    ┆ 3.58              ┆ 0.0134      ┆ 0.0134             ┆ 0.0                        ┆ 0.0134           ┆ 5.8334        │
│ 14:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 15:00:00     ┆ 5.655 ┆ 8.755     ┆ 8.7477  ┆ -0.0073            ┆ 5.655   ┆ 3.1               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 5.655         │
│ 15:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 15:30:00     ┆ 5.885 ┆ 8.755     ┆ 8.7477  ┆ -0.0073            ┆ 5.885   ┆ 2.87              ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 5.885         │
│ 15:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 16:00:00     ┆ 5.73  ┆ 8.43      ┆ 8.4608  ┆ 0.0308             ┆ 5.73    ┆ 2.7               ┆ 0.0209      ┆ 0.0209             ┆ 0.0                        ┆ 0.0209           ┆ 5.7509        │
│ 16:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 16:30:00     ┆ 4.655 ┆ 8.43      ┆ 8.4608  ┆ 0.0308             ┆ 4.655   ┆ 3.775             ┆ 0.017       ┆ 0.017              ┆ 0.0                        ┆ 0.017            ┆ 4.672         │
│ 16:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 17:00:00     ┆ 4.525 ┆ 8.105     ┆ 8.0738  ┆ -0.0312            ┆ 4.525   ┆ 3.58              ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 4.525         │
│ 17:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 17:30:00     ┆ 3.695 ┆ 7.78      ┆ 7.7869  ┆ 0.0069             ┆ 3.695   ┆ 4.085             ┆ 0.0033      ┆ 0.0033             ┆ 0.0                        ┆ 0.0033           ┆ 3.6983        │
│ 17:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 18:00:00     ┆ 4.04  ┆ 7.455     ┆ 10.9999 ┆ 3.5449             ┆ 4.04    ┆ 3.415             ┆ 1.921       ┆ 1.921              ┆ 0.0                        ┆ 1.921            ┆ 5.961         │
│ 18:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 18:30:00     ┆ 5.765 ┆ 7.135     ┆ 7.113   ┆ -0.022             ┆ 5.765   ┆ 1.37              ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 5.765         │
│ 18:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 19:00:00     ┆ 6.415 ┆ 7.135     ┆ 7.113   ┆ -0.022             ┆ 6.415   ┆ 0.72              ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 6.415         │
│ 19:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 19:30:00     ┆ 5.85  ┆ 6.81      ┆ 6.826   ┆ 0.016              ┆ 5.85    ┆ 0.96              ┆ 0.0137      ┆ 0.0137             ┆ 0.0                        ┆ 0.0137           ┆ 5.8637        │
│ 19:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 20:00:00     ┆ 5.25  ┆ 6.16      ┆ 6.1521  ┆ -0.0079            ┆ 5.25    ┆ 0.91              ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 5.25          │
│ 20:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 20:30:00     ┆ 4.44  ┆ 5.515     ┆ 5.4782  ┆ -0.0368            ┆ 4.44    ┆ 1.075             ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 4.44          │
│ 20:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 21:00:00     ┆ 4.455 ┆ 5.185     ┆ 6.2312  ┆ 1.0462             ┆ 4.455   ┆ 0.73              ┆ 0.8989      ┆ 0.8989             ┆ 0.0                        ┆ 0.8989           ┆ 5.3539        │
│ 21:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 21:30:00     ┆ 4.235 ┆ 4.865     ┆ 6.8843  ┆ 2.0193             ┆ 4.235   ┆ 0.63              ┆ 1.7578      ┆ 1.7578             ┆ 0.0                        ┆ 1.7578           ┆ 5.9928        │
│ 21:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 22:00:00     ┆ 4.09  ┆ 4.54      ┆ 5.4173  ┆ 0.8773             ┆ 4.09    ┆ 0.45              ┆ 0.7903      ┆ 0.7903             ┆ 0.0                        ┆ 0.7903           ┆ 4.8803        │
│ 22:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 22:30:00     ┆ 3.68  ┆ 4.215     ┆ 5.0804  ┆ 0.8654             ┆ 3.68    ┆ 0.535             ┆ 0.7556      ┆ 0.7556             ┆ 0.0                        ┆ 0.7556           ┆ 4.4356        │
│ 22:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 23:00:00     ┆ 4.05  ┆ 4.215     ┆ 5.0804  ┆ 0.8654             ┆ 4.05    ┆ 0.165             ┆ 0.8315      ┆ 0.8315             ┆ 0.0                        ┆ 0.8315           ┆ 4.8815        │
│ 23:00:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
│ 23:30:00     ┆ 3.51  ┆ 3.89      ┆ 4.6134  ┆ 0.7234             ┆ 3.51    ┆ 0.38              ┆ 0.6527      ┆ 0.6527             ┆ 0.0                        ┆ 0.6527           ┆ 4.1627        │
│ 23:30:00     ┆ 0.0   ┆ 0.0       ┆ 0.0     ┆ 0.0                ┆ 0.0     ┆ 0.0               ┆ 0.0         ┆ 0.0                ┆ 0.0                        ┆ 0.0              ┆ 0.0           │
└──────────────┴───────┴───────────┴─────────┴────────────────────┴─────────┴───────────────────┴─────────────┴────────────────────┴────────────────────────────┴──────────────────┴───────────────┘

In [25]:
import polars as pl

def view_hcm_daily_summary(df):
    print("🚀 TỔNG HỢP SỐ LIỆU NGÀY CHO SITE: Concentrix (Ho Chi Minh City)")
    
    # 1. Lọc Site HCM
    df_hcm = df.filter(pl.col("Site").str.contains("Ho Chi Minh"))
    
    if df_hcm.is_empty():
        print("❌ Không tìm thấy dữ liệu của Site HCM!")
        return

    # 2. Cộng dồn theo Ngày (Group by Date)
    # Các cột cần tính tổng
    target_cols = ["PSP", "MSP", "MSP site wise", "Final Billable", "Billable Loss"]
    # Chỉ lấy các cột thực sự có trong DataFrame
    valid_cols = [c for c in target_cols if c in df_hcm.columns]

    df_daily = df_hcm.group_by("Date").agg(
        [pl.col(c).sum() for c in valid_cols]
    ).sort("Date")

    # 3. Xoay bảng (Pivot) để hiển thị giống Excel
    # Dòng là Tên Chỉ Số, Cột là Ngày
    
    # Bước A: Unpivot (Chuyển cột thành dòng dữ liệu)
    df_long = df_daily.unpivot(
        index="Date", 
        variable_name="Metric", 
        value_name="Value"
    )
    
    # Bước B: Tạo cột ngày dạng chuỗi
    df_ready = df_long.with_columns(
        pl.col("Date").dt.strftime("%Y-%m-%d").alias("Date_Str")
    )

    # Bước C: Pivot (Metric làm dòng, Date làm cột)
    df_pivot = df_ready.pivot(
        values="Value",
        index="Metric",
        on="Date_Str",
        aggregate_function="sum",
        sort_columns=True
    )

    # 4. In kết quả
    print("\n📊 BẢNG TỔNG HỢP NGÀY (Đơn vị: Giờ)")
    # Cấu hình in rộng để thấy hết các ngày
    with pl.Config(tbl_rows=20, tbl_cols=20, float_precision=2, tbl_width_chars=300):
        print(df_pivot)

# =============================================================================
# CÁCH CHẠY:
# =============================================================================
if 'df_final' in locals():
    view_hcm_daily_summary(df_final)
elif 'df_result' in locals():
    view_hcm_daily_summary(df_result)
else:
    print("⚠️ Chưa có biến kết quả df_final/df_result. Hãy chạy code tính toán chính trước!")

🚀 TỔNG HỢP SỐ LIỆU NGÀY CHO SITE: Concentrix (Ho Chi Minh City)

📊 BẢNG TỔNG HỢP NGÀY (Đơn vị: Giờ)
shape: (5, 120)
┌────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ Metric         ┆ 2025-12-29 ┆ 2025-12-30 ┆ 2025-12-31 ┆ 2026-01-01 ┆ 2026-01-02 ┆ 2026-01-03 ┆ 2026-01-04 ┆ 2026-01-05 ┆ 2026-01-06 ┆ … ┆ 2026-04-17 ┆ 2026-04-18 ┆ 2026-04-19 ┆ 2026-04-20 ┆ 2026-04-21 ┆ 2026-04-22 ┆ 2026-04-23 ┆ 2026-04-24 ┆ 2026-04-25 ┆ 2026-04-26 │
│ ---            ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str            ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞════════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ PSP            ┆ 185.62     ┆ 248.90     ┆ 240.02     ┆ 382.94     ┆ 535.26     ┆ 513.99     ┆ 422.35     ┆ 565.56     ┆ 453.76     ┆ … ┆ 316.35     ┆ 289.12     ┆ 292.09     ┆ 355.00     ┆ 327.50     ┆ 316.00     ┆ 315.50     ┆ 277.50     ┆ 301.50     ┆ 328.00     │
│ MSP            ┆ 399.17     ┆ 359.22     ┆ 360.71     ┆ 684.71     ┆ 806.52     ┆ 783.15     ┆ 690.13     ┆ 839.00     ┆ 807.92     ┆ … ┆ 1027.80    ┆ 938.83     ┆ 891.46     ┆ 1138.71    ┆ 1211.72    ┆ 1233.85    ┆ 1179.41    ┆ 0.00       ┆ 0.00       ┆ 0.00       │
│ MSP site wise  ┆ 202.43     ┆ 252.22     ┆ 244.52     ┆ 382.96     ┆ 535.27     ┆ 514.01     ┆ 422.36     ┆ 565.61     ┆ 452.19     ┆ … ┆ 316.68     ┆ 289.48     ┆ 293.67     ┆ 357.52     ┆ 358.40     ┆ 341.43     ┆ 305.34     ┆ -0.00      ┆ -0.00      ┆ -0.00      │
│ Final Billable ┆ 225.44     ┆ 267.22     ┆ 296.57     ┆ 488.47     ┆ 603.39     ┆ 583.75     ┆ 451.27     ┆ 601.81     ┆ 472.49     ┆ … ┆ 306.02     ┆ 297.59     ┆ 257.44     ┆ 391.37     ┆ 374.37     ┆ 355.85     ┆ 248.50     ┆ -0.00      ┆ -0.00      ┆ -0.00      │
│ Billable Loss  ┆ 1.75       ┆ 6.13       ┆ 0.04       ┆ 1.31       ┆ 7.17       ┆ 11.20      ┆ 32.53      ┆ 4.29       ┆ 3.50       ┆ … ┆ 20.36      ┆ 11.74      ┆ 48.52      ┆ 5.61       ┆ 10.46      ┆ 9.77       ┆ 69.09      ┆ 0.00       ┆ 0.00       ┆ 0.00       │
└────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘